import { useEffect, useState } from 'react'
import { scheduling, type Calendar } from '../lib/scheduling'

/** Shared time-off grid used in the Teachers module. */
export function AvailabilityEditor({ value, onChange }: { value: Record<string, number[]>; onChange: (next: Record<string, number[]>) => void }) {
  const [calendar, setCalendar] = useState<Calendar | null>(null)
  useEffect(() => { let active = true; scheduling.calendar().then(data => { if (active) setCalendar(data) }).catch(() => { if (active) setCalendar({ days: [], periods: [] }) }); return () => { active = false } }, [])
  if (!calendar) return <p className="form__note">Loading time-off grid…</p>
  const days = calendar.days.filter(d => d.is_active), periods = calendar.periods.filter(p => p.is_teaching)
  if (!days.length || !periods.length) return <p className="form__note">Set up your working days and periods first to mark time off.</p>
  const isBlocked = (day: number, period: number) => (value[String(day)] ?? []).includes(period)
  function toggle(day: number, period: number) { const k = String(day); const current = new Set(value[k] ?? []); if (current.has(period)) current.delete(period); else current.add(period); const next = { ...value }; if (!current.size) delete next[k]; else next[k] = [...current].sort((a,b) => a-b); onChange(next) }
  const blocked = Object.values(value).flat().length
  return <fieldset className="availability"><legend className="field__label">Time off grid</legend><p className="field__hint">Green ✓ means available. Click a cell to switch it to red X for time off.</p><div className="availability__scroll"><table className="availability__table"><thead><tr><th scope="col"><span className="visually-hidden">Day</span></th>{periods.map(period => <th key={period.index} scope="col">{period.name}</th>)}</tr></thead><tbody>{days.map(day => <tr key={day.index}><th scope="row">{day.name}</th>{periods.map(period => { const checked = isBlocked(day.index, period.index); return <td key={period.index}><button type="button" className={`availability__cell availability__cell--${checked ? 'blocked' : 'available'}`} onClick={() => toggle(day.index, period.index)} aria-label={`${day.name} ${period.name} ${checked ? 'time off' : 'available'}`}><span className="availability__box" aria-hidden="true">{checked ? 'X' : '✓'}</span></button></td> })}</tr>)}</tbody></table></div>{blocked > 0 && <button type="button" className="button button--ghost button--sm" onClick={() => onChange({})}>Clear all</button>}<style>{`.availability__table{width:100%;border-collapse:collapse}.availability__table th,.availability__table td{border:1px solid #e2e8f0}.availability__table th{padding:.65rem;background:#f8fafc}.availability__table td{padding:0;background:#fff}.availability__cell{display:flex;width:100%;height:3.1rem;align-items:center;justify-content:center;padding:0;margin:0;border:0;border-radius:0;background:transparent;box-shadow:none;outline:none;cursor:pointer}.availability__cell:hover,.availability__cell:focus{background:transparent;box-shadow:none;outline:0}.availability__box{font-family:Arial,Helvetica,sans-serif;font-weight:700;font-size:2rem;line-height:1}.availability__cell--available .availability__box{color:#16a34a}.availability__cell--blocked .availability__box{color:#dc2626}`}</style></fieldset>
}
