import { useEffect, useState } from 'react'
import { scheduling, type Calendar } from '../lib/scheduling'

/** Teachers module time-off grid. Matches the dashboard Time Off grid. */
export function AvailabilityEditor({ value, onChange }: { value: Record<string, number[]>; onChange: (next: Record<string, number[]>) => void }) {
  const [calendar, setCalendar] = useState<Calendar | null>(null)
  useEffect(() => { let active = true; scheduling.calendar().then(data => { if (active) setCalendar(data) }).catch(() => { if (active) setCalendar({ days: [], periods: [] }) }); return () => { active = false } }, [])
  if (!calendar) return <p className="form__note">Loading time-off grid…</p>
  const days = calendar.days.filter(d => d.is_active), periods = calendar.periods.filter(p => p.is_teaching)
  if (!days.length || !periods.length) return <p className="form__note">Set up working days and periods first.</p>
  const isOff = (day: number, period: number) => (value[String(day)] ?? []).includes(period)
  function toggle(day: number, period: number) { const k = String(day); const current = new Set(value[k] ?? []); if (current.has(period)) current.delete(period); else current.add(period); const next = { ...value }; if (current.size) next[k] = [...current].sort((a,b) => a-b); else delete next[k]; onChange(next) }
  return <fieldset className="availability"><legend className="field__label">Time off grid</legend><div className="availability__scroll"><table className="availability__table"><thead><tr><th scope="col">DAY</th>{periods.map((p,i) => <th key={p.index} scope="col">P{i + 1}</th>)}</tr></thead><tbody>{days.map(day => <tr key={day.index}><th scope="row">{day.name}</th>{periods.map(period => { const off = isOff(day.index, period.index); return <td key={period.index}><button type="button" className="availability__cell" onClick={() => toggle(day.index, period.index)} aria-label={`${day.name} ${period.name}: ${off ? 'time off' : 'available'}`}>{off ? <span className="availability__x" aria-hidden="true">X</span> : <span className="availability__check" aria-hidden="true">✓</span>}</button></td> })}</tr>)}</tbody></table></div><style>{`.availability__table{width:100%;border-collapse:collapse}.availability__table th,.availability__table td{border:1px solid #e2e8f0}.availability__table th{padding:.65rem;background:#f8fafc}.availability__table td{padding:0;background:#fff}.availability__cell{display:flex;width:100%;height:3.1rem;align-items:center;justify-content:center;padding:0;margin:0;border:0;border-radius:0;background:transparent;box-shadow:none;outline:none;cursor:pointer}.availability__cell:hover,.availability__cell:focus{background:transparent;box-shadow:none;outline:0}.availability__check,.availability__x{font-family:Arial,Helvetica,sans-serif;font-weight:700;font-size:2rem;line-height:1}.availability__check{color:#16a34a}.availability__x{color:#dc2626}`}</style></fieldset>
}
