import { useCallback, useEffect, useState } from 'react'
import { Badge, ErrorState, LoadingBlock } from './States'
import { CloseIcon } from './icons'
import { useToast } from './Toast'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Day, type Event } from '../lib/scheduling'
const empty={name:'BREAK',start_time:'10:00',end_time:'10:20',day_indexes:[] as number[],event_type:'break',note:null as string|null}
export function TimetableEventsEditor(){
 const {notify}=useToast();const [days,setDays]=useState<Day[]>([]);const [events,setEvents]=useState<Event[]>([]);const [form,setForm]=useState({...empty});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);try{const [calendar,rows]=await Promise.all([scheduling.calendar(),scheduling.events()]);setDays(calendar.days.filter(d=>d.is_active));setEvents(rows)}catch(e){setError(friendlyApiError(e,'load timetable events'))}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 function toggleDay(index:number){setForm(f=>({...f,day_indexes:f.day_indexes.includes(index)?f.day_indexes.filter(d=>d!==index):[...f.day_indexes,index].sort((a,b)=>a-b)}))}
 async function save(){if(!form.day_indexes.length){notify('Select at least one applicable day.','error');return}setSaving(true);try{const row=await scheduling.createEvent(form);setEvents(rows=>{const other=rows.filter(e=>e.id!==row.id);return [...other,row].sort((a,b)=>a.start_time.localeCompare(b.start_time))});setForm({...empty});notify('Event saved. Matching days are stored on one recurring event.','success')}catch(e){notify(friendlyApiError(e,'save the timetable event'),'error')}finally{setSaving(false)}}
 async function remove(id:number){try{await scheduling.deleteEvent(id);setEvents(rows=>rows.filter(e=>e.id!==id));notify('Event removed.','success')}catch(e){notify(friendlyApiError(e,'remove the timetable event'),'error')}}
 if(loading)return <section className="card section"><LoadingBlock label="Loading timetable events" rows={3}/></section>
 if(error)return <section className="card section"><ErrorState title="Events could not load" message={error} onRetry={load}/></section>
 return <section className="card section"><div className="panel__head"><div><h2 className="section__title">Breaks and timetable events</h2><p className="form__note">Configure one event for every recurring schedule. Matching name, time and type automatically merge onto the same record.</p></div><Badge>{events.length} configured</Badge></div><div className="form__row"><div className="field"><label className="field__label">Name</label><input className="input" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></div><div className="field"><label className="field__label">Type</label><select className="input input--select" value={form.event_type} onChange={e=>setForm(f=>({...f,event_type:e.target.value}))}><option value="break">Break</option><option value="assembly">Assembly</option><option value="activity">Activity</option><option value="other">Other</option></select></div><div className="field"><label className="field__label">Start</label><input className="input" type="time" value={form.start_time} onChange={e=>setForm(f=>({...f,start_time:e.target.value}))}/></div><div className="field"><label className="field__label">End</label><input className="input" type="time" value={form.end_time} onChange={e=>setForm(f=>({...f,end_time:e.target.value}))}/></div></div><div className="form__row">{days.map(day=><label className="checkbox" key={day.index}><input type="checkbox" checked={form.day_indexes.includes(day.index)} onChange={()=>toggleDay(day.index)}/>{day.name}</label>)}</div><button type="button" className="button button--primary button--sm" onClick={save} disabled={saving}>{saving?'Saving…':'Add event'}</button><ul className="period-list" style={{marginTop:'1rem'}}>{events.map(event=><li className="period-row" key={event.id}><div><strong>{event.name}</strong><div className="form__note">{event.start_time}–{event.end_time} · {event.event_type} · {(event.day_indexes??[]).map(i=>days.find(d=>d.index===i)?.name??`Day ${i+1}`).join(', ')}</div></div><button type="button" className="icon-button icon-button--subtle" onClick={()=>remove(event.id)} aria-label={`Remove ${event.name}`}><CloseIcon width={16} height={16}/></button></li>)}</ul></section>
}
