import { useMemo, useState, type CSSProperties, type KeyboardEvent, type DragEvent } from 'react'
import type { Lesson, Period, Subject, Teacher, Room, Day, SchoolClass } from '../lib/scheduling'
import { LockIcon } from './icons'
import './timetable-time-grid.css'
import './timetable-subject-colours.css'
import './timetable-asc-toolbar.css'
import './timetable-three-view.css'

type LessonMeta = { subjects: Map<number, Subject>; teachers: Map<number, Teacher>; rooms: Map<number, Room>; classes: Map<number, SchoolClass> }
export type { LessonMeta }
export const UNASSIGNED_DRAG_TYPE = 'application/x-phikila-unassigned'
type ViewKind = 'whole-school' | 'class' | 'teacher' | 'generic'
type Props = { days: Day[]; periods: Period[]; lessons: Lesson[]; meta: LessonMeta; view?: ViewKind; conflicted?: Set<number>; selectedId?: number | null; readOnly?: boolean; zoom?: number; dense?: boolean; currentSlot?: { day: number; period: number } | null; onSelect?: (lesson: Lesson) => void; onMove?: (lesson: Lesson, day: number, period: number) => void; onResize?: (lesson: Lesson, duration: number) => void; onDropUnassigned?: (unassignedId: number, day: number, period: number) => void; secondary?: (lesson: Lesson) => string | null | undefined; teacherInitials?: boolean }

function minutes(value: string) { const [hour, minute] = value.split(':').map(Number); return hour * 60 + minute }
function initials(name: string | null | undefined) { return name?.trim().split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase() ?? '').join('') ?? '' }
const SUBJECT_COLOURS = ['#2563EB', '#7C3AED', '#DB2777', '#DC2626', '#EA580C', '#CA8A04', '#16A34A', '#0891B2', '#0F766E', '#4F46E5']
function colourFor(subject: Subject | undefined, index: number) { return subject?.colour && /^#[0-9A-Fa-f]{6}$/.test(subject.colour) ? subject.colour : SUBJECT_COLOURS[index % SUBJECT_COLOURS.length] }
function dayLabel(day: Day) { const item = day as Day & { date?: string; date_label?: string }; return item.date_label || item.date ? `${day.name} · ${item.date_label ?? item.date}` : day.name }
function classLabel(item: SchoolClass) { const grade = item.grade?.trim(); const stream = (item.stream ?? item.academic_stream)?.trim(); if (grade && stream) return `${grade} ${stream}`; return grade || item.name }

export function TimetableGrid({ days, periods, lessons, meta, view = 'whole-school', conflicted, selectedId, readOnly = false, zoom = 1, dense = false, currentSlot, onSelect, onMove, onResize, secondary, teacherInitials = false }: Props) {
  const [dragging, setDragging] = useState<Lesson | null>(null)
  const [carrying, setCarrying] = useState<Lesson | null>(null)
  const [hovered, setHovered] = useState<string | null>(null)
  const orderedPeriods = useMemo(() => [...periods].sort((a, b) => minutes(a.start_time) - minutes(b.start_time) || a.index - b.index), [periods])
  const activeDays = useMemo(() => days.filter((day) => day.is_active), [days])
  const subjectIndexes = useMemo(() => new Map([...meta.subjects.values()].sort((a, b) => a.id - b.id).map((subject, index) => [subject.id, index])), [meta.subjects])
  const bySlot = useMemo(() => { const result = new Map<string, Lesson[]>(); lessons.forEach((lesson) => { const key = `${lesson.day_index}:${lesson.period_index}`; result.set(key, [...(result.get(key) ?? []), lesson]) }); return result }, [lessons])
  const wholeRows = useMemo(() => [...meta.classes.values()].sort((a, b) => { const ag = a.grade ?? ''; const bg = b.grade ?? ''; return ag.localeCompare(bg, undefined, { numeric: true }) || classLabel(a).localeCompare(classLabel(b), undefined, { numeric: true }) }), [meta.classes])

  // The page historically did not pass an explicit view. Infer the intended projection from the active filter: a class projection has no secondary class label, while a teacher projection has exactly one teacher and still shows the assigned class.
  const effectiveView = useMemo<ViewKind>(() => {
    if (view !== 'whole-school') return view
    if (!lessons.length) return 'whole-school'
    if (secondary && lessons.every((lesson) => secondary(lesson) == null)) return 'class'
    const teacherIds = new Set(lessons.map((lesson) => lesson.teacher_id).filter((id): id is number => id != null))
    if (secondary && teacherIds.size === 1) return 'teacher'
    return 'whole-school'
  }, [view, lessons, secondary])

  const moveLesson = (lesson: Lesson, day: number, period: number) => { if (readOnly || lesson.is_locked) return; onMove?.(lesson, day, period); setDragging(null); setCarrying(null); setHovered(null) }
  const handleCellKeyDown = (event: KeyboardEvent, day: number, period: number, cellLessons: Lesson[]) => { if (readOnly || (event.key !== 'Enter' && event.key !== ' ')) return; event.preventDefault(); if (carrying) return moveLesson(carrying, day, period); const lesson = cellLessons.find((item) => !item.is_locked) ?? cellLessons[0]; if (lesson) { onSelect?.(lesson); if (!lesson.is_locked) setCarrying(lesson) } }
  const renderCard = (lesson: Lesson, compact = false) => { const subject = meta.subjects.get(lesson.subject_id); const teacher = lesson.teacher_id ? meta.teachers.get(lesson.teacher_id) : null; const room = lesson.room_id ? meta.rooms.get(lesson.room_id) : null; const context = secondary?.(lesson); const teacherCode = teacher?.code?.trim() || teacher?.staff_number?.trim() || ''; const subjectColour = colourFor(subject, subjectIndexes.get(lesson.subject_id) ?? 0); const conflict = conflicted?.has(lesson.id) ?? false; const style = { '--subject-colour': subjectColour, backgroundColor: conflict ? '#FBE8E5' : `${subjectColour}1A`, borderLeftColor: conflict ? '#9A2F24' : subjectColour } as CSSProperties; return <div key={lesson.id} className={['lesson-card', compact ? 'lesson-card--compact' : '', selectedId === lesson.id ? 'lesson-card--selected' : '', conflict ? 'lesson-card--conflict' : '', lesson.is_locked ? 'lesson-card--locked' : '', carrying?.id === lesson.id ? 'lesson-card--carrying' : ''].filter(Boolean).join(' ')} style={style} draggable={!readOnly && !lesson.is_locked} onDragStart={(event) => { if (lesson.is_locked) { event.preventDefault(); return }; setDragging(lesson); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', String(lesson.id)) }} onDragEnd={() => setDragging(null)} onClick={() => onSelect?.(lesson)} role="button" tabIndex={-1} aria-label={`${subject?.name ?? 'Lesson'}${context ? `, ${context}` : ''}`}> <span className="lesson-card__subject" style={{ color: subjectColour }}>{subject?.code ?? subject?.name ?? 'Lesson'}</span>{(effectiveView === 'whole-school' || effectiveView === 'teacher' || effectiveView === 'generic') && context && <span className="lesson-card__line">{context}</span>}{effectiveView === 'class' && teacherCode && <span className="lesson-card__line">{teacherCode}</span>}{effectiveView === 'class' && room?.name && <span className="lesson-card__line lesson-card__room">{room.name}</span>}{effectiveView === 'teacher' && teacherInitials && teacher?.name && <span className="lesson-card__line">{initials(teacher.name)}</span>}{conflict && <span className="lesson-card__flag">Conflict</span>}{lesson.is_locked && <span className="lesson-card__lock" title="Locked"><LockIcon width={12} height={12} /></span>}{!readOnly && !lesson.is_locked && onResize && <button type="button" className="lesson-card__resize" title="Extend lesson" aria-label="Extend lesson" onClick={(event) => { event.stopPropagation(); onResize(lesson, Math.min(10, (lesson.duration ?? 1) + 1)) }} />}</div> }
  const wholeColumns = Math.max(1, activeDays.length * Math.max(1, orderedPeriods.length))
  const wholeStyle = { '--tt-period-count': orderedPeriods.length || 1, '--tt-whole-columns': wholeColumns } as CSSProperties
  const timeStyle = { '--tt-columns': orderedPeriods.map((period) => `${Math.max(1, minutes(period.end_time) - minutes(period.start_time))}fr`).join(' ') } as CSSProperties
  const slotHandlers = (key: string, day: number, period: number, isBreak: boolean) => ({ onDragOver: (event: DragEvent) => { if (readOnly || isBreak || !dragging) return; event.preventDefault(); setHovered(key) }, onDragLeave: () => setHovered((value) => value === key ? null : value), onDrop: (event: DragEvent) => { event.preventDefault(); if (!isBreak && dragging) moveLesson(dragging, day, period) } })
  const wholeSchoolGrid = <div className="timetable__whole-school-grid" style={wholeStyle}><div className="timetable__whole-corner">Grade / Stream</div>{activeDays.map((day) => <div key={`head-${day.index}`} className="timetable__whole-day-head" style={{ gridColumn: `span ${Math.max(1, orderedPeriods.length)}` }}>{dayLabel(day)}</div>)}<div className="timetable__whole-corner timetable__whole-period-row-label">Period / Time</div>{activeDays.flatMap((day) => orderedPeriods.map((period) => <div key={`period-${day.index}-${period.index}`} className={`timetable__whole-period-head ${!period.is_teaching ? 'timetable__period-head--break' : ''}`}><span className="timetable__period">{period.name}</span><span className="timetable__clock">{period.start_time}–{period.end_time}</span></div>))}{wholeRows.map((row) => <div key={row.id} className="timetable__whole-row"><div className="timetable__whole-class-label">{classLabel(row)}</div>{activeDays.flatMap((day) => orderedPeriods.map((period) => { const key = `whole:${row.id}:${day.index}:${period.index}`; const cellLessons = lessons.filter((lesson) => lesson.class_id === row.id && lesson.day_index === day.index && lesson.period_index === period.index); const isBreak = !period.is_teaching; const isTarget = hovered === key && Boolean(dragging || carrying); return <div key={`${row.id}-${day.index}-${period.index}`} className={['timetable__whole-slot', isBreak ? 'timetable__whole-slot--break' : '', currentSlot?.day === day.index && currentSlot.period === period.index ? 'timetable__whole-slot--now' : '', isTarget ? 'timetable__cell--target' : ''].filter(Boolean).join(' ')} aria-label={`${classLabel(row)}, ${dayLabel(day)}, ${period.name}`} {...slotHandlers(key, day.index, period.index, isBreak)}>{isBreak ? <span className="timetable__whole-break">{period.name}</span> : cellLessons.map((lesson) => renderCard(lesson, true))}</div> }))}</div>)}</div>
  const dayPeriodGrid = <><div className="timetable__time-grid" style={timeStyle}><div className="timetable__corner">Day / Date</div>{orderedPeriods.map((period) => <div key={period.index} className={`timetable__period-head ${!period.is_teaching ? 'timetable__period-head--break' : ''}`}><span className="timetable__period">{period.name}</span><span className="timetable__clock">{period.start_time}–{period.end_time}</span></div>)}{activeDays.map((day) => <div key={day.index} className="timetable__day-row"><div className="timetable__day-label">{dayLabel(day)}</div>{orderedPeriods.map((period) => { const key = `${day.index}:${period.index}`; const cellLessons = bySlot.get(key) ?? []; const isBreak = !period.is_teaching; const isTarget = hovered === key && Boolean(dragging || carrying); return <div key={period.index} className={['timetable__cell', isBreak ? 'timetable__cell--break' : '', currentSlot?.day === day.index && currentSlot.period === period.index ? 'timetable__cell--now' : '', isTarget ? 'timetable__cell--target' : '', cellLessons.length === 0 ? 'timetable__cell--empty' : ''].filter(Boolean).join(' ')} tabIndex={readOnly ? -1 : 0} aria-label={`${dayLabel(day)}, ${period.name}`} onKeyDown={(event) => handleCellKeyDown(event, day.index, period.index, cellLessons)} {...slotHandlers(key, day.index, period.index, isBreak)}>{isBreak ? <span className="timetable__break-vertical">{period.name}</span> : cellLessons.map((lesson) => renderCard(lesson))}</div> })}</div>)}</div></>
  return <div className={['timetable', `timetable--zoom-${zoom === 0.75 ? '75' : zoom === 1.25 ? '125' : '100'}`, dense ? 'timetable--dense' : '', `timetable--${effectiveView}-view`].join(' ')}>{effectiveView === 'whole-school' ? wholeSchoolGrid : dayPeriodGrid}</div>
}
