"""Reconcile scheduling runtime tables with the canonical ORM contract.

The affected production tables are currently empty, so the type/constraint
reconciliation below is safe without data conversion. Legacy columns are
retained rather than dropped. No synthetic school_id is introduced.
"""

from alembic import op
import sqlalchemy as sa

revision = "20260817tt01"
down_revision = "f8a1c2d3e4b5"
branch_labels = None
depends_on = None


def _add_identity_if_missing(table: str, column: str) -> None:
    bind = op.get_bind()
    default = bind.execute(
        sa.text(
            "SELECT column_default FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name=:table AND column_name=:column"
        ),
        {"table": table, "column": column},
    ).scalar_one_or_none()
    if default is None:
        bind.execute(
            sa.text(
                f"ALTER TABLE public.{table} ALTER COLUMN {column} "
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            )
        )


def upgrade() -> None:
    bind = op.get_bind()

    # These tables are empty in the audited production database. Therefore the
    # integer conversions do not rewrite or truncate legitimate timetable data.
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs "
        "ALTER COLUMN id TYPE integer USING id::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs "
        "ALTER COLUMN progress TYPE integer USING progress::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN progress SET DEFAULT 0"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN progress SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN school_id DROP DEFAULT"
    ))
    _add_identity_if_missing("tt_solver_jobs", "id")

    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements "
        "ALTER COLUMN id TYPE integer USING id::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN class_id SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN subject_id SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN school_id DROP DEFAULT"
    ))
    _add_identity_if_missing("tt_lesson_requirements", "id")

    # tt_audit: add the fields used by the runtime ORM/job writer. Existing
    # user_id/detail fields are retained for compatibility rather than dropped.
    inspector = sa.inspect(bind)
    audit_columns = {c["name"] for c in inspector.get_columns("tt_audit")}
    additions = {
        "updated_at": "TIMESTAMPTZ DEFAULT now()",
        "actor": "VARCHAR(160)",
        "entity_id": "INTEGER",
        "summary": "TEXT",
        "at": "TIMESTAMPTZ DEFAULT now()",
        "school_id": "INTEGER",
    }
    for name, definition in additions.items():
        if name not in audit_columns:
            bind.execute(sa.text(
                f"ALTER TABLE public.tt_audit ADD COLUMN {name} {definition}"
            ))

    bind.execute(sa.text("ALTER TABLE public.tt_audit ALTER COLUMN id TYPE integer USING id::integer"))
    _add_identity_if_missing("tt_audit", "id")
    bind.execute(sa.text("ALTER TABLE public.tt_audit ALTER COLUMN school_id DROP DEFAULT"))
    bind.execute(sa.text("ALTER TABLE public.tt_audit ALTER COLUMN school_id SET NOT NULL"))
    bind.execute(sa.text("ALTER TABLE public.tt_audit ALTER COLUMN at SET DEFAULT now()"))


def downgrade() -> None:
    # Intentionally non-destructive. Reversing these changes could destroy data
    # after the tables become populated.
    pass
