"""Reconcile scheduling runtime tables with the canonical ORM contract."""

from alembic import op
import sqlalchemy as sa

revision = "20260817tt01"
down_revision = "20260817183310"
branch_labels = None
depends_on = None


def _add_identity_if_missing(table: str, column: str) -> None:
    bind = op.get_bind()
    default = bind.execute(
        sa.text(
            "SELECT column_default FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name=:table AND column_name=:column"
        ),
        {"table": table, "column": column},
    ).scalar_one_or_none()
    if default is None:
        bind.execute(sa.text(
            f"ALTER TABLE public.{table} ALTER COLUMN {column} ADD GENERATED BY DEFAULT AS IDENTITY"
        ))


def upgrade() -> None:
    bind = op.get_bind()

    # Production was audited with zero rows in these three tables. Keep legacy
    # columns and avoid synthetic tenant assignments.
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN id TYPE integer USING id::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN progress TYPE integer USING progress::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN progress SET DEFAULT 0"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN progress SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_solver_jobs ALTER COLUMN school_id DROP DEFAULT"
    ))
    _add_identity_if_missing("tt_solver_jobs", "id")

    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN id TYPE integer USING id::integer"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN class_id SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN subject_id SET NOT NULL"
    ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_lesson_requirements ALTER COLUMN school_id DROP DEFAULT"
    ))
    _add_identity_if_missing("tt_lesson_requirements", "id")

    # Keep legacy user_id/detail columns; add the fields consumed by the runtime.
    inspector = sa.inspect(bind)
    audit_columns = {c["name"] for c in inspector.get_columns("tt_audit")}
    additions = {
        "updated_at": "TIMESTAMPTZ DEFAULT now()",
        "actor": "VARCHAR(160)",
        "entity_id": "INTEGER",
        "summary": "TEXT",
        "at": "TIMESTAMPTZ DEFAULT now()",
        "school_id": "INTEGER",
    }
    for name, definition in additions.items():
        if name not in audit_columns:
            bind.execute(sa.text(
                f"ALTER TABLE public.tt_audit ADD COLUMN {name} {definition}"
            ))
    bind.execute(sa.text(
        "ALTER TABLE public.tt_audit ALTER COLUMN id TYPE integer USING id::integer"
    ))
    _add_identity_if_missing("tt_audit", "id")
    bind.execute(sa.text("ALTER TABLE public.tt_audit ALTER COLUMN school_id DROP DEFAULT"))


def downgrade() -> None:
    # Deliberately non-destructive; reversing types/constraints can destroy data.
    pass
