"""Add school module models

Revision ID: 43fea8e527aa
Revises: 4c7888868b57
Create Date: 2026-08-05 10:21:46.578674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fea8e527aa'
down_revision: Union[str, Sequence[str], None] = '4c7888868b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('stamp_path', sa.String(length=255), nullable=True),
    sa.Column('report_header', sa.Text(), nullable=True),
    sa.Column('report_footer', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_index(op.f('ix_school_branding_id'), 'school_branding', ['id'], unique=False)
    op.create_table('school_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=True),
    sa.Column('deputy_principal', sa.String(length=255), nullable=True),
    sa.Column('bursar', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_index(op.f('ix_school_contact_id'), 'school_contact', ['id'], unique=False)
    op.drop_index(op.f('ix_school_working_days_id'), table_name='school_working_days')
    op.drop_table('school_working_days')
    op.add_column('school_info', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('school_info', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('school_info', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('school_info', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('school_info', sa.Column('county', sa.String(length=100), nullable=True))
    op.add_column('school_info', sa.Column('sub_county', sa.String(length=100), nullable=True))
    op.add_column('school_info', sa.Column('ward', sa.String(length=100), nullable=True))
    op.add_column('school_info', sa.Column('postal_address', sa.String(length=255), nullable=True))
    op.add_column('school_info', sa.Column('physical_address', sa.Text(), nullable=True))
    op.add_column('school_info', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('school_info', sa.Column('alternative_phone', sa.String(length=50), nullable=True))
    op.add_column('school_info', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('school_info', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('school_info', sa.Column('vision', sa.Text(), nullable=True))
    op.add_column('school_info', sa.Column('mission', sa.Text(), nullable=True))
    op.add_column('school_info', sa.Column('principal_name', sa.String(length=255), nullable=True))
    op.add_column('school_info', sa.Column('established_year', sa.Integer(), nullable=True))
    op.add_column('school_info', sa.Column('logo', sa.String(length=255), nullable=True))
    op.add_column('school_info', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('school_info', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('school_info', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_school_info_school_code'), table_name='school_info')
    op.drop_index(op.f('ix_school_info_school_name'), table_name='school_info')
    op.create_index(op.f('ix_school_info_code'), 'school_info', ['code'], unique=True)
    op.create_index(op.f('ix_school_info_name'), 'school_info', ['name'], unique=False)
    op.create_unique_constraint(None, 'school_info', ['registration_number'])
    op.drop_column('school_info', 'logo_url')
    op.drop_column('school_info', 'school_code')
    op.drop_column('school_info', 'contact_details')
    op.drop_column('school_info', 'address')
    op.drop_column('school_info', 'school_name')
    op.add_column('school_settings', sa.Column('school_id', sa.Integer(), nullable=False))
    op.add_column('school_settings', sa.Column('timezone', sa.String(length=100), nullable=False))
    op.add_column('school_settings', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('school_settings', sa.Column('date_format', sa.String(length=50), nullable=False))
    op.add_column('school_settings', sa.Column('time_format', sa.String(length=50), nullable=False))
    op.add_column('school_settings', sa.Column('language', sa.String(length=50), nullable=False))
    op.add_column('school_settings', sa.Column('allow_multiple_sessions', sa.Boolean(), nullable=False))
    op.add_column('school_settings', sa.Column('default_lesson_duration', sa.Integer(), nullable=False))
    op.add_column('school_settings', sa.Column('current_academic_year_id', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('school_settings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'school_settings', ['school_id'])
    op.create_foreign_key(None, 'school_settings', 'school_info', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_settings', type_='foreignkey')
    op.drop_constraint(None, 'school_settings', type_='unique')
    op.drop_column('school_settings', 'updated_at')
    op.drop_column('school_settings', 'created_at')
    op.drop_column('school_settings', 'current_academic_year_id')
    op.drop_column('school_settings', 'default_lesson_duration')
    op.drop_column('school_settings', 'allow_multiple_sessions')
    op.drop_column('school_settings', 'language')
    op.drop_column('school_settings', 'time_format')
    op.drop_column('school_settings', 'date_format')
    op.drop_column('school_settings', 'currency')
    op.drop_column('school_settings', 'timezone')
    op.drop_column('school_settings', 'school_id')
    op.add_column('school_info', sa.Column('school_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('school_info', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('school_info', sa.Column('contact_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('school_info', sa.Column('school_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('school_info', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'school_info', type_='unique')
    op.drop_index(op.f('ix_school_info_name'), table_name='school_info')
    op.drop_index(op.f('ix_school_info_code'), table_name='school_info')
    op.create_index(op.f('ix_school_info_school_name'), 'school_info', ['school_name'], unique=True)
    op.create_index(op.f('ix_school_info_school_code'), 'school_info', ['school_code'], unique=True)
    op.drop_column('school_info', 'updated_at')
    op.drop_column('school_info', 'created_at')
    op.drop_column('school_info', 'is_active')
    op.drop_column('school_info', 'logo')
    op.drop_column('school_info', 'established_year')
    op.drop_column('school_info', 'principal_name')
    op.drop_column('school_info', 'mission')
    op.drop_column('school_info', 'vision')
    op.drop_column('school_info', 'website')
    op.drop_column('school_info', 'email')
    op.drop_column('school_info', 'alternative_phone')
    op.drop_column('school_info', 'phone')
    op.drop_column('school_info', 'physical_address')
    op.drop_column('school_info', 'postal_address')
    op.drop_column('school_info', 'ward')
    op.drop_column('school_info', 'sub_county')
    op.drop_column('school_info', 'county')
    op.drop_column('school_info', 'category')
    op.drop_column('school_info', 'registration_number')
    op.drop_column('school_info', 'code')
    op.drop_column('school_info', 'name')
    op.create_table('school_working_days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('school_working_days_pkey'))
    )
    op.create_index(op.f('ix_school_working_days_id'), 'school_working_days', ['id'], unique=False)
    op.drop_index(op.f('ix_school_contact_id'), table_name='school_contact')
    op.drop_table('school_contact')
    op.drop_index(op.f('ix_school_branding_id'), table_name='school_branding')
    op.drop_table('school_branding')
    # ### end Alembic commands ###
