"""add class registers and update models

Revision ID: 4721a8a1f38d
Revises: e3e43c2c32aa
Create Date: 2026-07-26 14:52:45.232589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4721a8a1f38d'
down_revision: Union[str, Sequence[str], None] = 'e3e43c2c32aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tsc_number', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_index(op.f('ix_teachers_tsc_number'), 'teachers', ['tsc_number'], unique=True)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_id'), 'qualifications', ['id'], unique=False)
    op.create_table('class_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('grade_form_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['grade_form_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_registers_id'), 'class_registers', ['id'], unique=False)
    op.drop_index(op.f('ix_grade_levels_id'), table_name='grade_levels')
    op.drop_table('grade_levels')
    op.drop_index(op.f('ix_terms_id'), table_name='terms')
    op.drop_table('terms')
    op.add_column('academic_years', sa.Column('year', sa.String(), nullable=True))
    op.drop_constraint(op.f('academic_years_name_key'), 'academic_years', type_='unique')
    op.create_index(op.f('ix_academic_years_year'), 'academic_years', ['year'], unique=True)
    op.drop_column('academic_years', 'name')
    op.add_column('streams', sa.Column('name', sa.String(), nullable=True))
    op.add_column('streams', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_streams_name'), 'streams', ['name'], unique=False)
    op.create_foreign_key(None, 'streams', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streams', type_='foreignkey')
    op.drop_index(op.f('ix_streams_name'), table_name='streams')
    op.drop_column('streams', 'level_id')
    op.drop_column('streams', 'name')
    op.add_column('academic_years', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_academic_years_year'), table_name='academic_years')
    op.create_unique_constraint(op.f('academic_years_name_key'), 'academic_years', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('academic_years', 'year')
    op.create_table('terms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('terms_pkey'))
    )
    op.create_index(op.f('ix_terms_id'), 'terms', ['id'], unique=False)
    op.create_table('grade_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('grade_levels_pkey'))
    )
    op.create_index(op.f('ix_grade_levels_id'), 'grade_levels', ['id'], unique=False)
    op.drop_index(op.f('ix_class_registers_id'), table_name='class_registers')
    op.drop_table('class_registers')
    op.drop_index(op.f('ix_qualifications_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_teachers_tsc_number'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
