"""fresh start school info

Revision ID: 8b4a887cf966
Revises: 
Create Date: 2026-07-26 10:52:01.124772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4a887cf966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=False)
    op.create_table('grade_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_levels_id'), 'grade_levels', ['id'], unique=False)
    op.create_table('lesson_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_periods_id'), 'lesson_periods', ['id'], unique=False)
    op.create_table('school_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('school_code', sa.String(), nullable=False),
    sa.Column('school_type', sa.String(), nullable=True),
    sa.Column('education_system', sa.String(), nullable=True),
    sa.Column('motto', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_info_id'), 'school_info', ['id'], unique=False)
    op.create_index(op.f('ix_school_info_school_code'), 'school_info', ['school_code'], unique=True)
    op.create_index(op.f('ix_school_info_school_name'), 'school_info', ['school_name'], unique=True)
    op.create_table('school_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_settings_id'), 'school_settings', ['id'], unique=False)
    op.create_table('school_working_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_working_days_id'), 'school_working_days', ['id'], unique=False)
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_id'), 'streams', ['id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_id'), 'terms', ['id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_register_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_academic_year_id'), 'timetable_entries', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_class_register_id'), 'timetable_entries', ['class_register_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_day_of_week'), 'timetable_entries', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetable_entries_id'), 'timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_period_id'), 'timetable_entries', ['period_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_subject_id'), 'timetable_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_teacher_id'), 'timetable_entries', ['teacher_id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index(op.f('ix_timetables_term_id'), 'timetables', ['term_id'], unique=False)
    op.create_table('working_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_days_day_name'), 'working_days', ['day_name'], unique=True)
    op.create_index(op.f('ix_working_days_id'), 'working_days', ['id'], unique=False)
    op.create_table('timetable_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_allocations_id'), 'timetable_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_allocations_id'), table_name='timetable_allocations')
    op.drop_table('timetable_allocations')
    op.drop_index(op.f('ix_working_days_id'), table_name='working_days')
    op.drop_index(op.f('ix_working_days_day_name'), table_name='working_days')
    op.drop_table('working_days')
    op.drop_index(op.f('ix_timetables_term_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_timetable_entries_teacher_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_subject_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_period_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_day_of_week'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_class_register_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_academic_year_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_terms_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_streams_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_school_working_days_id'), table_name='school_working_days')
    op.drop_table('school_working_days')
    op.drop_index(op.f('ix_school_settings_id'), table_name='school_settings')
    op.drop_table('school_settings')
    op.drop_index(op.f('ix_school_info_school_name'), table_name='school_info')
    op.drop_index(op.f('ix_school_info_school_code'), table_name='school_info')
    op.drop_index(op.f('ix_school_info_id'), table_name='school_info')
    op.drop_table('school_info')
    op.drop_index(op.f('ix_lesson_periods_id'), table_name='lesson_periods')
    op.drop_table('lesson_periods')
    op.drop_index(op.f('ix_grade_levels_id'), table_name='grade_levels')
    op.drop_table('grade_levels')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
