import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { LoadingBlock } from '../components/States'
import { api, friendlyApiError, type AcademicYear } from '../lib/api'

type Item = { student_id:number; admission_number:string; student_name:string; current_grade_name:string|null; current_stream_name:string|null; action:string; target_grade_id:number|null; target_grade_name:string|null; target_level_id:number|null; target_stream_id:number|null; target_stream_name:string|null; target_options:Array<{id:number;name:string;code?:string|null}> }
const actions=[['promote','Promote'],['repeat','Repeat'],['graduate','Graduate'],['transfer','Transfer'],['review','Review']] as const

export default function AcademicYearTransitionPage(){
 const [years,setYears]=useState<AcademicYear[]>([]); const [fromId,setFromId]=useState(''); const [toId,setToId]=useState(''); const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [done,setDone]=useState<string|null>(null)
 useEffect(()=>{api.academicYears().then(ys=>{setYears(ys);const cur=ys.find(y=>y.is_current)||ys[0];setFromId(cur?String(cur.id):'');const next=ys.find(y=>y.id!==cur?.id);setToId(next?String(next.id):'')}).catch(e=>setError(friendlyApiError(e,'load academic years')))},[])
 async function preview(){if(!fromId||!toId||fromId===toId)return;setLoading(true);setError(null);setDone(null);try{const x=await api.academicTransitionPreview(Number(fromId),Number(toId));setItems(x.students||[])}catch(e){setError(friendlyApiError(e,'prepare the transition'))}finally{setLoading(false)}}
 useEffect(()=>{void preview()},[fromId,toId])
 function change(i:number,patch:Partial<Item>){setItems(v=>v.map((x,n)=>n===i?{...x,...patch}:x))}
 async function confirm(){if(!fromId||!toId||!items.length)return;setSaving(true);setError(null);try{const result=await api.academicTransition({from_year_id:Number(fromId),to_year_id:Number(toId),decisions:items.map(x=>({student_id:x.student_id,action:x.action,target_grade_id:x.target_grade_id,target_level_id:x.target_level_id,target_stream_id:x.target_stream_id}))});setDone('Transition completed. '+result.transitioned+' student enrollments created.');await preview()}catch(e){setError(friendlyApiError(e,'complete the transition'))}finally{setSaving(false)}}
 return <div><PageHeader title="Academic Year Transition" description="Move students into a new academic year without rewriting historical enrollments." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Academic Year Transition'}]}/>
 {error&&<Alert tone="error">{error}</Alert>}{done&&<Alert tone="success">{done}</Alert>}
 <section className="card section"><h2 className="section__title">Transition setup</h2><div style={{display:'flex',gap:'var(--space-3)',flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 16rem'}}><span className="field__label">From academic year</span><select className="input" value={fromId} onChange={e=>setFromId(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' (Current)':''}</option>)}</select></label><label className="field" style={{flex:'1 1 16rem'}}><span className="field__label">To academic year</span><select className="input" value={toId} onChange={e=>setToId(e.target.value)}>{years.filter(y=>String(y.id)!==fromId).map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label></div></section>
 {loading?<LoadingBlock label="Preparing student transition" rows={6}/>:items.length>0&&<section className="card section"><div className="section__header"><div><h2 className="section__title">Review students</h2><p className="section__description">Confirm promotion, repetition, graduation, transfer, or review before committing.</p></div><button className="button button--primary" disabled={saving} onClick={()=>void confirm()}>{saving?'Processing…':'Confirm transition'}</button></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.875rem'}}><thead><tr><th style={{textAlign:'left',padding:'var(--space-2)'}}>Student</th><th style={{textAlign:'left',padding:'var(--space-2)'}}>Current</th><th style={{textAlign:'left',padding:'var(--space-2)'}}>Action</th><th style={{textAlign:'left',padding:'var(--space-2)'}}>New grade</th><th style={{textAlign:'left',padding:'var(--space-2)'}}>Stream</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.student_id} style={{borderTop:'1px solid var(--color-line)'}}><td style={{padding:'var(--space-2)'}}><strong>{x.student_name}</strong><br/><small>{x.admission_number}</small></td><td style={{padding:'var(--space-2)'}}>{x.current_grade_name||'—'}{x.current_stream_name?' / '+x.current_stream_name:''}</td><td style={{padding:'var(--space-2)'}}><select className="input" value={x.action} onChange={e=>change(i,{action:e.target.value})}>{actions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td style={{padding:'var(--space-2)'}}>{(x.action==='promote'||x.action==='repeat')?(x.target_grade_name||'Needs review'):'—'}</td><td style={{padding:'var(--space-2)'}}>{(x.action==='promote'||x.action==='repeat')&&x.target_options.length>0?<select className="input" value={x.target_stream_id??''} onChange={e=>change(i,{target_stream_id:e.target.value?Number(e.target.value):null,target_stream_name:x.target_options.find(s=>String(s.id)===e.target.value)?.name||null})}><option value="">No stream</option>{x.target_options.map(s=><option key={s.id} value={s.id}>{s.name}{s.code?' — '+s.code:''}</option>)}</select>:x.target_stream_name||'—'}</td></tr>)}</tbody></table></div></section>}</div>
}
