import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, LoadingBlock } from '../components/States'
import { api, type AcademicYear, type Level, type SchoolClassSetup, type StudentListItem } from '../lib/api'
import { examinations, type ExamEntry, type ExamSubject, type Examination } from '../lib/examinations'
import { scheduling, type Subject } from '../lib/scheduling'
import { friendlyApiError, apiFetch } from '../lib/api'

type Row={student:StudentListItem;score:number;percentage:number;grade:string|null;rank:number}
const nameOf=(s:StudentListItem)=>[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' ')
const genderOf=(s:StudentListItem)=>(s.gender||'').trim().toUpperCase()

export default function ClassResultsPage(){
 const [exams,setExams]=useState<Examination[]>([]);const [years,setYears]=useState<AcademicYear[]>([]);const [levels,setLevels]=useState<Level[]>([]);const [classes,setClasses]=useState<SchoolClassSetup[]>([]);const [subjects,setSubjects]=useState<Subject[]>([]);const [students,setStudents]=useState<StudentListItem[]>([]);const [assignments,setAssignments]=useState<ExamSubject[]>([]);const [entries,setEntries]=useState<ExamEntry[]>([]);const [examId,setExamId]=useState('');const [yearId,setYearId]=useState('');const [levelId,setLevelId]=useState('');const [classId,setClassId]=useState('');const [subjectId,setSubjectId]=useState('');const [gender,setGender]=useState('ALL');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{void Promise.all([examinations.list(),api.academicYears(),api.levels(),api.schoolClasses(),scheduling.subjects()]).then(([e,y,l,c,s])=>{setExams(e);setYears(y);setLevels(l);setClasses(c);setSubjects(s);const cy=y.find(x=>x.is_current)??y[0];if(cy)setYearId(String(cy.id));if(e[0])setExamId(String(e[0].id))}).catch(err=>setError(friendlyApiError(err,'load class results'))).finally(()=>setLoading(false))},[])
 const visibleClasses=useMemo(()=>classes.filter(c=>(!yearId||c.academic_year_id===Number(yearId))&&(!levelId||c.level_id===Number(levelId))),[classes,yearId,levelId]);const classAssignments=useMemo(()=>assignments.filter(a=>(!yearId||a.academic_year_id===Number(yearId))&&(!levelId||a.level_id===Number(levelId))&&(!classId||a.school_class_id===Number(classId))),[assignments,yearId,levelId,classId])
 useEffect(()=>{if(!examId)return;void examinations.listSubjects(Number(examId)).then(setAssignments).catch(err=>setError(friendlyApiError(err,'load exam subjects')))},[examId])
 useEffect(()=>{if(!classId||!yearId){setStudents([]);return}void apiFetch<{items:StudentListItem[]}>(`/api/v1/students?academic_year_id=${yearId}&class_id=${classId}&page=1&page_size=100`).then(x=>setStudents(x.items??[])).catch(err=>setError(friendlyApiError(err,'load class learners')))},[classId,yearId])
 useEffect(()=>{if(!examId||!subjectId){setEntries([]);return}setBusy(true);void examinations.listEntries(Number(examId),Number(subjectId)).then(setEntries).catch(err=>setError(friendlyApiError(err,'load subject results'))).finally(()=>setBusy(false))},[examId,subjectId])
 useEffect(()=>{if(!subjectId&&classAssignments.length)setSubjectId(String(classAssignments[0].subject_id))},[classAssignments,subjectId])
 const selectedAssignment=classAssignments.find(a=>a.subject_id===Number(subjectId));const selectedSubject=subjects.find(s=>s.id===Number(subjectId));const entryMap=useMemo(()=>new Map(entries.map(e=>[e.student_id,e])),[entries]);const genderOptions=useMemo(()=>['ALL',...Array.from(new Set(students.map(genderOf).filter(Boolean)))],[students]);
 const ranked=useMemo<Row[]>(()=>{if(!selectedAssignment)return [];const eligible=students.filter(s=>gender==='ALL'||genderOf(s)===gender);return eligible.map(s=>{const e=entryMap.get(s.id);const score=e?.score;return score==null?null:{student:s,score,percentage:e?.percentage??(score/selectedAssignment.total_marks)*100,grade:e?.grade??null,rank:0}}).filter(Boolean).sort((a,b)=>b!.score-a!.score||b!.percentage-a!.percentage||nameOf(a!.student).localeCompare(nameOf(b!.student))).map((r,i)=>({...r!,rank:i+1}))},[selectedAssignment,students,entryMap,gender]);const mean=ranked.length?ranked.reduce((sum,r)=>sum+r.percentage,0)/ranked.length:0
 if(loading)return <LoadingBlock label="Loading class results" rows={6}/>
 return <div><PageHeader title="Class Results & Rankings" description="View learners and subject rankings for a canonical school class." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Examinations',to:'/examinations'},{label:'Class Results'}]} actions={<button className="button button--secondary" disabled={!ranked.length} onClick={()=>window.print()}>Print ranking</button>}/>{error&&<Alert tone="error">{error}</Alert>}
 <section className="card section no-print"><h2 className="section__title">Class selection</h2><div className="form form--grid"><Select label="Examination" value={examId} options={exams.map(x=>[x.id,x.name])} onChange={setExamId}/><Select label="Academic year" value={yearId} options={years.map(x=>[x.id,x.name])} onChange={v=>{setYearId(v);setClassId('')}}/><Select label="Level" value={levelId} options={levels.map(x=>[x.id,x.name])} onChange={v=>{setLevelId(v);setClassId('')}}/><Select label="School class" value={classId} options={visibleClasses.map(x=>[x.id,`${x.name} · ${x.code}`])} onChange={setClassId}/></div>{!classId?<EmptyState title="Select a school class" description="Choose a canonical school class to view its examination results."/>:!classAssignments.length?<EmptyState title="No subject assignments" description="Assign subjects to this school class for the selected examination first."/>:<div className="form form--grid"><Select label="Subject / Learning area" value={subjectId} options={classAssignments.map(a=>[a.subject_id,subjects.find(s=>s.id===a.subject_id)?.name??`Subject ${a.subject_id}`])} onChange={setSubjectId}/><Select label="Gender" value={gender} options={genderOptions.map(x=>[x,x==='ALL'?'All genders':x])} onChange={setGender}/></div>}</section>
 {classId&&selectedAssignment&&(busy?<LoadingBlock label="Calculating rankings" rows={8}/>:!ranked.length?<EmptyState title="No ranked marks" description="No marks have been entered for the selected class, subject and gender filter."/>:<section className="section class-ranking-print"><div className="card" style={{padding:'var(--space-4)',marginBottom:'var(--space-3)'}}><h2>{classes.find(c=>c.id===Number(classId))?.name||'School class'} · {selectedSubject?.name||'Subject'}</h2><p>{exams.find(e=>e.id===Number(examId))?.name} · {gender==='ALL'?'All genders':gender}</p><div style={{display:'flex',gap:'1.5rem',flexWrap:'wrap'}}><div>LEARNERS <strong>{ranked.length}</strong></div><div>MEAN <strong>{mean.toFixed(1)}%</strong></div><div>TOP SCORE <strong>{ranked[0].score}/{selectedAssignment.total_marks}</strong></div></div></div><div className="card" style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>POSITION</th><th>ADMISSION NO.</th><th>LEARNER</th><th>GENDER</th><th>SCORE</th><th>%</th><th>OUTCOME</th></tr></thead><tbody>{ranked.map(r=><tr key={r.student.id}><td><strong>{r.rank}/{ranked.length}</strong></td><td>{r.student.admission_number}</td><td>{nameOf(r.student)}</td><td>{r.student.gender||'—'}</td><td><strong>{r.score}</strong> / {selectedAssignment.total_marks}</td><td>{r.percentage.toFixed(1)}%</td><td><Badge tone={r.grade?.startsWith('EE')?'success':r.grade?.startsWith('AE')?'warning':'info'}>{r.grade||'—'}</Badge></td></tr>)}</tbody></table></div></section>)}
 <style>{`@media print{.no-print,.sidebar,.topbar,.bottom-nav,.print-footer{display:none!important}.class-ranking-print{margin:0!important}.class-ranking-print .card{box-shadow:none!important;border:0!important}.app-shell,.app-shell__main,.app-shell__content{display:block!important;margin:0!important;padding:0!important}}`}</style></div>
}
function Select({label,value,options,onChange}:{label:string;value:string;options:Array<[number|string,string]>;onChange:(value:string)=>void}){return <label className="field"><span className="field__label">{label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select {label.toLowerCase()}</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
