import { useCallback, useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, LoadingBlock } from '../components/States'
import { api, type AcademicYear, type Grade, type Level, type Stream, type StudentListItem } from '../lib/api'
import { apiFetch, friendlyApiError } from '../lib/api'
import { examinations, type ExamEntry, type ExamSeries, type Examination, type ExamSubject, type ResultsAnalysis, type StudentResult } from '../lib/examinations'

type Tab = 'setup' | 'marks' | 'results'

export default function ExaminationsPage() {
  const [series, setSeries] = useState<ExamSeries[]>([])
  const [exams, setExams] = useState<Examination[]>([])
  const [selected, setSelected] = useState<Examination | null>(null)
  const [tab, setTab] = useState<Tab>('setup')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    setLoading(true); setError(null)
    try { const [s, e] = await Promise.all([examinations.listSeries(), examinations.list()]); setSeries(s); setExams(e) }
    catch (err) { setError(friendlyApiError(err, 'load examinations')) }
    finally { setLoading(false) }
  }, [])
  useEffect(() => { load() }, [load])

  return <div>
    <PageHeader title="Examinations" description="Configure examinations, enter marks, review results, and publish safely." />
    {error && <Alert tone="error">{error}</Alert>}
    <div className="card" style={{ padding: 'var(--space-2)', marginBottom: 'var(--space-4)', display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap' }}>
      {(['setup', 'marks', 'results'] as Tab[]).map(item => <button key={item} className={`button button--sm ${tab === item ? 'button--primary' : 'button--secondary'}`} onClick={() => setTab(item)}>{item === 'setup' ? 'Examination Setup' : item === 'marks' ? 'Mark Entry' : 'Results & Report Cards'}</button>)}
    </div>
    {loading ? <LoadingBlock label="Loading examinations" rows={5} /> : tab === 'setup' ? <SetupTab series={series} exams={exams} onRefresh={load} onSelect={exam => setSelected(exam)} /> : !selected ? <EmptyState title="Select an examination" description="Choose an examination from Setup first, then open Mark Entry or Results." /> : tab === 'marks' ? <MarkEntryTab exam={selected} /> : <ResultsTab exam={selected} />}
  </div>
}

function SetupTab({ series, exams, onRefresh, onSelect }: { series: ExamSeries[]; exams: Examination[]; onRefresh: () => void; onSelect: (e: Examination) => void }) {
  const [showSeries, setShowSeries] = useState(false); const [showExam, setShowExam] = useState(false); const [message, setMessage] = useState<string | null>(null)
  async function changeStatus(exam: Examination, next: 'draft' | 'active' | 'published' | 'locked') { try { const updated = await examinations.setStatus(exam.id, next); setMessage(`${updated.name} is now ${updated.status}.`); onRefresh() } catch (err) { setMessage(friendlyApiError(err, 'change examination status')) } }
  return <>
    {message && <Alert tone="info">{message}</Alert>}
    <section className="section"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 className="section__title">Exam Series</h2><button className="button button--secondary button--sm" onClick={() => setShowSeries(!showSeries)}>+ Series</button></div>
      {showSeries && <NewSeriesForm onCreated={() => { setShowSeries(false); onRefresh() }} onCancel={() => setShowSeries(false)} />}
      {!series.length ? <EmptyState title="No exam series" description="Create a series before adding examinations." /> : <div style={{ display: 'grid', gap: 'var(--space-2)' }}>{series.map(s => <div className="card" key={s.id} style={{ padding: 'var(--space-3)', display: 'flex', justifyContent: 'space-between' }}><strong>{s.name}</strong><Badge tone={s.status === 'active' ? 'success' : 'warning'}>{s.status}</Badge></div>)}</div>}
    </section>
    <section className="section"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 className="section__title">Examinations</h2><button className="button button--primary button--sm" disabled={!series.length} onClick={() => setShowExam(!showExam)}>+ Examination</button></div>
      {showExam && <NewExamForm series={series} onCreated={() => { setShowExam(false); onRefresh() }} onCancel={() => setShowExam(false)} />}
      {!exams.length ? <EmptyState title="No examinations" description="Create an examination to begin configuration." /> : <div style={{ display: 'grid', gap: 'var(--space-2)' }}>{exams.map(exam => <div className="card" key={exam.id} style={{ padding: 'var(--space-3)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 'var(--space-3)', flexWrap: 'wrap' }}><div><strong>{exam.name}</strong><div style={{ color: 'var(--color-ink-muted)', fontSize: '.85rem' }}>{exam.exam_date || 'No date'} · {exam.total_marks} marks · Pass {exam.passing_marks}</div></div><Badge tone={exam.status === 'published' ? 'success' : exam.status === 'locked' ? 'info' : 'warning'}>{exam.status}</Badge></div><div style={{ display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap', marginTop: 'var(--space-3)' }}><button className="button button--secondary button--sm" onClick={() => onSelect(exam)}>Select</button>{exam.status === 'draft' && <button className="button button--secondary button--sm" onClick={() => changeStatus(exam, 'active')}>Open for marks</button>}{exam.status === 'active' && <button className="button button--secondary button--sm" onClick={() => changeStatus(exam, 'published')}>Publish</button>}{exam.status === 'published' && <button className="button button--secondary button--sm" onClick={() => changeStatus(exam, 'locked')}>Lock</button>}</div></div>)}</div>}
    </section>
    {exams.map(exam => <ConfigurationPanel key={exam.id} exam={exam} onUpdated={onRefresh} />)}
  </>
}

function ConfigurationPanel({ exam, onUpdated }: { exam: Examination; onUpdated: () => void }) {
  const [open, setOpen] = useState(false); const [subjects, setSubjects] = useState<ExamSubject[]>([]); const [years, setYears] = useState<AcademicYear[]>([]); const [levels, setLevels] = useState<Level[]>([]); const [grades, setGrades] = useState<Grade[]>([]); const [streams, setStreams] = useState<Stream[]>([]); const [message, setMessage] = useState<string | null>(null)
  const [form, setForm] = useState({ subject_id: '', academic_year_id: '', level_id: '', grade_id: '', stream_id: '', teacher_id: '', total_marks: '100' })
  useEffect(() => { if (!open) return; Promise.all([examinations.listSubjects(exam.id), api.academicYears(), api.levels()]).then(([s, y, l]) => { setSubjects(s); setYears(y); setLevels(l) }).catch(e => setMessage(friendlyApiError(e, 'load examination configuration'))) }, [open, exam.id])
  useEffect(() => { if (form.level_id) api.grades(Number(form.level_id)).then(setGrades).catch(() => setGrades([])); else setGrades([]) }, [form.level_id])
  useEffect(() => { if (form.academic_year_id && form.grade_id) api.streams(Number(form.academic_year_id), Number(form.grade_id)).then(setStreams).catch(() => setStreams([])); else setStreams([]) }, [form.academic_year_id, form.grade_id])
  async function assign() { try { await examinations.assignSubject(exam.id, { subject_id: Number(form.subject_id), academic_year_id: Number(form.academic_year_id), level_id: Number(form.level_id), grade_id: Number(form.grade_id), stream_id: Number(form.stream_id), teacher_id: form.teacher_id ? Number(form.teacher_id) : null, total_marks: Number(form.total_marks) }); setMessage('Subject assigned.'); setSubjects(await examinations.listSubjects(exam.id)); onUpdated() } catch (e) { setMessage(friendlyApiError(e, 'assign subject')) } }
  return <div className="card section" style={{ marginTop: 'var(--space-3)' }}><button className="button button--ghost button--sm" onClick={() => setOpen(!open)}>{open ? 'Hide' : 'Configure'} {exam.name}</button>{open && <div style={{ marginTop: 'var(--space-3)' }}>{message && <Alert tone="info">{message}</Alert>}<h3>Subject assignments</h3><p style={{ color: 'var(--color-ink-muted)', fontSize: '.85rem' }}>Use the existing subject and teacher IDs; academic year, level, grade and stream are selected from the canonical academic context.</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(12rem,1fr))', gap: 'var(--space-2)' }}>{[['Subject ID','subject_id'],['Teacher ID (optional)','teacher_id'],['Maximum marks','total_marks']].map(([label,key]) => <label className="field" key={key}><span className="field__label">{label}</span><input className="input" type="number" min="0" value={(form as any)[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<Select label="Academic year" value={form.academic_year_id} options={years.map(x => [x.id,x.name])} onChange={v => setForm({...form,academic_year_id:v,grade_id:'',stream_id:''})}/><Select label="Level" value={form.level_id} options={levels.map(x => [x.id,x.name])} onChange={v => setForm({...form,level_id:v,grade_id:'',stream_id:''})}/><Select label="Grade" value={form.grade_id} options={grades.map(x => [x.id,x.name])} onChange={v => setForm({...form,grade_id:v,stream_id:''})}/><Select label="Stream" value={form.stream_id} options={streams.map(x => [x.id,x.name])} onChange={v => setForm({...form,stream_id:v})}/></div><button className="button button--primary button--sm" disabled={!form.subject_id||!form.academic_year_id||!form.level_id||!form.grade_id||!form.stream_id} onClick={assign}>Assign subject</button><div style={{ marginTop: 'var(--space-3)', overflowX: 'auto' }}><table style={{width:'100%'}}><thead><tr><th>Subject ID</th><th>Academic context</th><th>Teacher</th><th>Marks</th></tr></thead><tbody>{subjects.map(s=><tr key={s.id}><td>{s.subject_id}</td><td>{s.grade_id} / {s.stream_id}</td><td>{s.teacher_id ?? '—'}</td><td>{s.total_marks}</td></tr>)}</tbody></table></div></div>}</div>
}

function MarkEntryTab({ exam }: { exam: Examination }) {
  const [subjects, setSubjects] = useState<ExamSubject[]>([]); const [students, setStudents] = useState<StudentListItem[]>([]); const [subjectId, setSubjectId] = useState(''); const [scores, setScores] = useState<Record<number,string>>({}); const [remarks, setRemarks] = useState<Record<number,string>>({}); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => { examinations.listSubjects(exam.id).then(setSubjects).catch(e=>setMessage(friendlyApiError(e,'load mark entry'))) }, [exam.id])
  const subject = subjects.find(s => s.subject_id === Number(subjectId)); const max = subject?.total_marks ?? exam.total_marks
  useEffect(() => { if (!subject) { setStudents([]); return }; const q = new URLSearchParams({ page:'1', page_size:'100', academic_year_id:String(subject.academic_year_id), level_id:String(subject.level_id), grade_id:String(subject.grade_id), stream_id:String(subject.stream_id) }); Promise.all([apiFetch<{items:StudentListItem[];total:number}>(`/api/v1/students?${q.toString()}`), examinations.listEntries(exam.id, subject.subject_id)]).then(([st, rows]) => { setStudents(st.items); const next:Record<number,string>={}; const rem:Record<number,string>={}; rows.forEach(r=>{if(r.score!=null)next[r.student_id]=String(r.score);if(r.remarks)rem[r.student_id]=r.remarks}); setScores(next); setRemarks(rem) }).catch(e=>setMessage(friendlyApiError(e,'load marks'))) }, [exam.id, subject])
  const save = async () => { if (!subject) return; setBusy(true); try { const entries = Object.entries(scores).filter(([,v])=>v!=='').map(([id,v])=>({student_id:Number(id),subject_id:subject.subject_id,score:Number(v),remarks:remarks[Number(id)]||null})); const result=await examinations.enterScores(exam.id,entries); setMessage(`Saved ${result.created+result.updated} marks.`) } catch(e){setMessage(friendlyApiError(e,'save marks'))} finally{setBusy(false)} }
  return <section className="section"><h2 className="section__title">Mark Entry — {exam.name}</h2>{message&&<Alert tone="info">{message}</Alert>}<div style={{display:'flex',gap:'var(--space-2)',alignItems:'end',marginBottom:'var(--space-3')}}><Select label="Subject assignment" value={subjectId} options={subjects.map(s=>[s.subject_id,`Subject ${s.subject_id} · Grade ${s.grade_id} · Stream ${s.stream_id}`])} onChange={setSubjectId}/><Badge tone={exam.status==='active'?'success':'warning'}>{exam.status}</Badge></div>{!subject?<EmptyState title="Select a subject" description="Choose a configured subject to load students from its exact academic context."/>:<><div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Admission</th><th>Student</th><th>Score / {max}</th><th>Remarks</th></tr></thead><tbody>{students.map(st=><tr key={st.id}><td>{st.admission_number}</td><td>{st.first_name} {st.last_name}</td><td><input className="input" style={{maxWidth:'8rem'}} type="number" min="0" max={max} value={scores[st.id]??''} onChange={e=>setScores({...scores,[st.id]:e.target.value})}/></td><td><input className="input" value={remarks[st.id]??''} onChange={e=>setRemarks({...remarks,[st.id]:e.target.value})}/></td></tr>)}</tbody></table></div><button className="button button--primary" disabled={busy||exam.status!=='active'||!students.length} onClick={save}>{busy?'Saving…':'Save marks'}</button>{exam.status!=='active'&&<p style={{color:'var(--color-ink-muted)'}}>Mark entry is available only while the examination is active.</p>}</>}</section>
}

function ResultsTab({ exam }: { exam: Examination }) { const [results,setResults]=useState<StudentResult[]>([]);const [analysis,setAnalysis]=useState<ResultsAnalysis|null>(null);const [selected,setSelected]=useState<StudentResult|null>(null);const [message,setMessage]=useState<string|null>(null);useEffect(()=>{Promise.all([examinations.generateResults(exam.id),examinations.resultsAnalysis(exam.id)]).then(([r,a])=>{setResults(r);setAnalysis(a)}).catch(e=>setMessage(friendlyApiError(e,'generate results')))},[exam.id]);return <section className="section">{message&&<Alert tone="error">{message}</Alert>}<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap'}}><h2 className="section__title">Results — {exam.name}</h2><button className="button button--secondary button--sm" onClick={()=>window.print()}>Print</button></div>{analysis&&<div style={{display:'flex',gap:'var(--space-2)',flexWrap:'wrap',marginBottom:'var(--space-3')}}><Badge tone="info">Students: {analysis.cohort_size}</Badge><Badge tone="info">Cohort mean: {analysis.cohort_mean ?? '—'}%</Badge>{Object.entries(analysis.band_distribution).map(([k,v])=><Badge key={k}>{k}: {v}</Badge>)}<Badge tone="success">Improved: {analysis.progress_summary.improved??0}</Badge><Badge tone="warning">Declined: {analysis.progress_summary.declined??0}</Badge></div>}<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>#</th><th>Admission</th><th>Name</th><th>Total</th><th>Average</th><th>Mean %</th><th>Band</th><th>Progress</th><th></th></tr></thead><tbody>{results.map(r=><tr key={r.student_id}><td>{r.position}</td><td>{r.admission_number}</td><td>{r.student_name}</td><td>{r.total_score}</td><td>{r.average}</td><td>{r.percentage??'—'}</td><td>{r.band??'—'}</td><td>{r.progress??'—'}</td><td><button className="button button--ghost button--sm" onClick={()=>setSelected(r)}>Report card</button></td></tr>)}</tbody></table></div>{selected&&<ReportCard result={selected} exam={exam} onClose={()=>setSelected(null)}/>}</section> }

function ReportCard({result,exam,onClose}:{result:StudentResult;exam:Examination;onClose:()=>void}){return <div className="card section" style={{marginTop:'var(--space-4)'}}><div style={{display:'flex',justifyContent:'space-between'}}><h3>Report Card</h3><button className="button button--ghost button--sm" onClick={onClose}>Close</button></div><p><strong>{result.student_name}</strong> · {result.admission_number}</p><p>{exam.name} · Position {result.position??'—'} · Average {result.average}% · Band {result.band??'—'}</p><table style={{width:'100%'}}><thead><tr><th>Subject</th><th>Score</th><th>%</th><th>Grade/Band</th></tr></thead><tbody>{result.subject_scores.map(s=><tr key={s.subject_id}><td>{s.subject_id}</td><td>{s.score}</td><td>{s.percentage??'—'}</td><td>{s.grade??s.band??'—'}</td></tr>)}</tbody></table><button className="button button--primary button--sm" onClick={()=>window.print()}>Print report card</button></div>}

function Select({label,value,options,onChange}:{label:string;value:string;options:[number,string][];onChange:(v:string)=>void}){return <label className="field" style={{minWidth:'12rem'}}><span className="field__label">{label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
function NewSeriesForm({onCreated,onCancel}:{onCreated:()=>void;onCancel:()=>void}){const[name,setName]=useState('');const[error,setError]=useState('');const save=async()=>{try{await examinations.createSeries({name:name.trim()});onCreated()}catch(e){setError(friendlyApiError(e,'create exam series'))}};return <div className="card" style={{padding:'var(--space-3)',margin:'var(--space-3) 0'}}>{error&&<Alert tone="error">{error}</Alert>}<div style={{display:'flex',gap:'var(--space-2)'}}><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. 2026 Term 2"/><button className="button button--primary" disabled={!name.trim()} onClick={save}>Create</button><button className="button button--secondary" onClick={onCancel}>Cancel</button></div></div>}
function NewExamForm({series,onCreated,onCancel}:{series:ExamSeries[];onCreated:()=>void;onCancel:()=>void}){const[form,setForm]=useState({series_id:series[0]?.id||0,name:'',exam_date:'',total_marks:100,passing_marks:50});const[error,setError]=useState('');const save=async()=>{if(form.passing_marks>form.total_marks){setError('Passing marks cannot exceed total marks.');return}try{await examinations.create(form);onCreated()}catch(e){setError(friendlyApiError(e,'create examination'))}};return <div className="card" style={{padding:'var(--space-3)',margin:'var(--space-3) 0'}}>{error&&<Alert tone="error">{error}</Alert>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(12rem,1fr))',gap:'var(--space-2)'}}><Select label="Series" value={String(form.series_id)} options={series.map(s=>[s.id,s.name])} onChange={v=>setForm({...form,series_id:Number(v)})}/><label className="field"><span className="field__label">Exam name</span><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span className="field__label">Date</span><input className="input" type="date" value={form.exam_date} onChange={e=>setForm({...form,exam_date:e.target.value})}/></label><label className="field"><span className="field__label">Total marks</span><input className="input" type="number" min="1" value={form.total_marks} onChange={e=>setForm({...form,total_marks:Number(e.target.value)})}/></label><label className="field"><span className="field__label">Pass marks</span><input className="input" type="number" min="0" value={form.passing_marks} onChange={e=>setForm({...form,passing_marks:Number(e.target.value)})}/></label></div><div style={{marginTop:'var(--space-2)',display:'flex',gap:'var(--space-2)'}}><button className="button button--primary" disabled={!form.name.trim()} onClick={save}>Create</button><button className="button button--secondary" onClick={onCancel}>Cancel</button></div></div>}
