import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge } from '../components/States'
import { useToast } from '../components/Toast'
import { Link, useNavigate } from '../lib/router'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Calendar, type Job } from '../lib/scheduling'

const DAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const TERMINAL = new Set(['completed', 'failed', 'cancelled'])

export function GenerateProfilePage() {
  const { notify } = useToast(); const navigate = useNavigate()
  const [calendar, setCalendar] = useState<Calendar | null>(null); const [label, setLabel] = useState('Weekdays Timetable'); const [days, setDays] = useState<number[]>([]); const [seconds, setSeconds] = useState(30); const [job, setJob] = useState<Job | null>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true)
  const [summary, setSummary] = useState<{ requirements: number; constraints: number; teachers: number; classes: number; rooms: number } | null>(null)
  useEffect(() => { let mounted = true; Promise.all([scheduling.calendar(), scheduling.requirements(), scheduling.constraints(), scheduling.teachers(), scheduling.classes(), scheduling.rooms()]).then(([week, requirements, constraints, teachers, classes, rooms]) => { if (!mounted) return; setCalendar(week); setDays(week.days.filter((day) => day.is_active).map((day) => day.index)); setSummary({ requirements: requirements.length, constraints: constraints.length, teachers: teachers.length, classes: classes.length, rooms: rooms.length }) }).catch((error) => notify(friendlyApiError(error, 'load timetable generation setup'), 'error')).finally(() => { if (mounted) setLoading(false) }); return () => { mounted = false } }, [notify])
  useEffect(() => { if (!job || TERMINAL.has(job.status)) return; const timer = window.setInterval(() => { void scheduling.job(job.id).then(setJob).catch(() => undefined) }, 1200); return () => window.clearInterval(timer) }, [job])
  useEffect(() => { if (job?.status === 'completed' && job.result_version_id) { notify('Timetable generated successfully.', 'success'); navigate('/timetable') } }, [job, navigate, notify])
  const teachingPeriods = calendar?.periods.filter((period) => period.is_teaching).length ?? 0
  const selectedDays = useMemo(() => days.map((index) => calendar?.days.find((day) => day.index === index)?.name ?? DAY_NAMES[index]).join(', '), [calendar, days])
  const active = job && !TERMINAL.has(job.status); const canGenerate = !loading && !busy && !active && Boolean(label.trim()) && days.length > 0 && Boolean(summary?.requirements)
  function toggle(day: number) { setDays((current) => current.includes(day) ? current.filter((value) => value !== day) : [...current, day].sort((a, b) => a - b)) }
  async function generate() { if (!canGenerate) return; setBusy(true); try { const result = await scheduling.generateProfile({ max_seconds: seconds, label: label.trim(), day_indexes: days }); setJob(result); notify('Timetable generation started.', 'success') } catch (error) { notify(friendlyApiError(error, 'generate the timetable'), 'error') } finally { setBusy(false) } }
  async function cancel() { if (!job || TERMINAL.has(job.status)) return; try { setJob(await scheduling.cancelJob(job.id)); notify('Generation cancelled.', 'success') } catch (error) { notify(friendlyApiError(error, 'cancel generation'), 'error') } }
  return <>
    <PageHeader title="Generate timetable" description="Configure the generation run, review the scheduling inputs, then create an independent timetable without replacing the current one." breadcrumbs={[{ label: 'Dashboard', to: '/' }, { label: 'Timetable', to: '/timetable' }, { label: 'Generate' }]} actions={<Link className="button button--secondary button--sm" to="/timetable">Open timetable</Link>} />
    <section className="card section"><div className="toolbar"><div><h2 className="section__title">1. Timetable profile</h2><p className="section__description">A profile keeps its own working-day selection and does not change the school's shared calendar.</p></div>{calendar && <Badge>{days.length} days · {teachingPeriods} teaching periods/day</Badge>}</div><div className="form form--grid"><div className="field form--grid__full"><label className="field__label" htmlFor="timetable-name">Timetable name</label><input id="timetable-name" className="input" value={label} maxLength={120} onChange={(event) => setLabel(event.target.value)} placeholder="e.g. Term 1 Master Timetable" /></div><div className="field form--grid__full"><label className="field__label">Working days</label><p className="form__note">Select the days available to this generated timetable.</p><div className="chip-toggles">{DAY_NAMES.map((name, index) => <label key={name} className={`chip-toggle ${days.includes(index) ? 'chip-toggle--on' : ''}`}><input type="checkbox" checked={days.includes(index)} onChange={() => toggle(index)} />{name}</label>)}</div>{days.length > 0 && <span className="form__note">Selected: {selectedDays}</span>}</div><div className="field"><label className="field__label" htmlFor="optimisation-time">Optimisation effort</label><select id="optimisation-time" className="input input--select" value={seconds} onChange={(event) => setSeconds(Number(event.target.value))}><option value={10}>Quick — 10 seconds</option><option value={30}>Balanced — 30 seconds</option><option value={60}>Thorough — 60 seconds</option><option value={120}>Maximum — 2 minutes</option></select><span className="form__note">More time gives the optimiser more opportunity to improve soft preferences.</span></div></div></section>
    <section className="card section"><div className="toolbar"><div><h2 className="section__title">2. Generation inputs</h2><p className="section__description">These are the resources and rules the solver will use.</p></div></div>{summary ? <div className="chip-list"><Badge>{summary.requirements} lesson requirements</Badge><Badge>{summary.teachers} teachers</Badge><Badge>{summary.classes} classes</Badge><Badge>{summary.rooms} rooms</Badge><Badge>{summary.constraints} scheduling rules</Badge></div> : <p className="form__note">Loading generation inputs…</p>}{summary && summary.requirements === 0 && <Alert tone="info" title="No lesson requirements">Add teaching allocations before generating a timetable. <Link to="/scheduling/requirements">Open lesson requirements</Link>.</Alert>}<div className="form__row" style={{ marginTop: 16 }}><Link className="button button--ghost button--sm" to="/scheduling/requirements">Lesson requirements</Link><Link className="button button--ghost button--sm" to="/scheduling/constraints">Generation rules</Link><Link className="button button--ghost button--sm" to="/scheduling/time-off">Time Off / availability</Link></div></section>
    <section className="card section"><div className="toolbar"><div><h2 className="section__title">3. Generate</h2><p className="section__description">Hard conflicts and availability remain enforced; weighted rules are optimisation preferences.</p></div></div><div className="chip-list"><Badge tone={days.length ? 'success' : 'info'}>{days.length ? `${days.length} working days` : 'Select at least one day'}</Badge><Badge tone={summary?.requirements ? 'success' : 'info'}>{summary?.requirements ? 'Lesson requirements ready' : 'Lesson requirements missing'}</Badge><Badge>Double lessons validated</Badge><Badge>Teacher/class/room conflicts checked</Badge></div><div className="form__row" style={{ marginTop: 18 }}><button type="button" className="button button--primary" onClick={() => void generate()} disabled={!canGenerate}>{busy || active ? 'Generating…' : 'Create and generate timetable'}</button>{active && <button type="button" className="button button--secondary" onClick={() => void cancel()}>Cancel generation</button>}</div></section>
    {job && <section className="card section"><div className="toolbar"><div><h2 className="section__title">Generation monitor</h2><p className="section__description">Job #{job.id} · {job.stage ?? job.status}</p></div><Badge tone={job.status === 'failed' ? 'info' : 'success'}>{job.status}</Badge></div><div className="progress" aria-label={`Generation ${job.progress}%`}><div className="progress__bar" style={{ width: `${Math.max(0, Math.min(100, job.progress))}%` }} /></div><p className="form__note">{job.progress}% complete{job.message ? ` · ${job.message}` : ''}</p>{job.checks.length > 0 && <div className="chip-list">{job.checks.map((check) => <Badge key={check.key} tone={check.state === 'failed' ? 'info' : check.state === 'passed' ? 'success' : 'neutral'}>{check.label}: {check.state}</Badge>)}</div>}{job.status === 'failed' && <Alert tone="error" title="Generation failed">{job.message ?? 'The solver could not produce a valid timetable. Review the failed checks, relax a rule, or add more capacity and try again.'}</Alert>}{job.status === 'cancelled' && <Alert tone="info" title="Generation cancelled">No new timetable was published.</Alert>}{job.status === 'completed' && <Alert tone="success" title="Timetable generated">The new timetable is ready for review. It remains independent until you publish it.</Alert>}</section>}
  </>
}
