import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge } from '../components/States'
import { useToast } from '../components/Toast'
import { useNavigate } from '../lib/router'
import { apiFetch, friendlyApiError } from '../lib/api'
import { scheduling, type Calendar, type Job } from '../lib/scheduling'
const DAY_NAMES=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
export function GenerateProfilePage(){
 const {notify}=useToast();const navigate=useNavigate();const [calendar,setCalendar]=useState<Calendar|null>(null);const [label,setLabel]=useState('Weekdays Timetable');const [days,setDays]=useState<number[]>([]);const [seconds,setSeconds]=useState(30);const [job,setJob]=useState<Job|null>(null);const [busy,setBusy]=useState(false)
 useEffect(()=>{void scheduling.calendar().then(c=>{setCalendar(c);setDays(c.days.filter(d=>d.is_active).map(d=>d.index))}).catch(e=>notify(friendlyApiError(e,'load working days'),'error'))},[notify])
 function toggle(day:number){setDays(v=>v.includes(day)?v.filter(d=>d!==day):[...v,day].sort((a,b)=>a-b))}
 async function generate(){if(busy||!label.trim()||!days.length)return;setBusy(true);try{const result=await apiFetch<Job>('/api/v1/scheduling/solver/generate-profile',{method:'POST',body:JSON.stringify({max_seconds:seconds,label:label.trim(),day_indexes:days})});setJob(result);if(result.status==='completed'){notify('New timetable generated.','success');navigate('/timetable')}else if(result.status==='failed')notify(result.message||'Generation failed.','error')}catch(e){notify(friendlyApiError(e,'generate the timetable'),'error')}finally{setBusy(false)}}
 return <><PageHeader title="New timetable" description="Create an independent timetable without replacing any existing timetable." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable',to:'/timetable'},{label:'New'}]}/><section className="card section"><h2 className="section__title">Timetable details</h2><div className="field"><label htmlFor="timetable-name">Timetable name</label><input id="timetable-name" className="input" value={label} maxLength={120} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Weekend Timetable"/></div><div className="field"><label>Working days for this timetable</label><p className="form__note">These days are saved with this timetable. They do not change the school's shared working-week settings.</p><div className="chip-toggles">{DAY_NAMES.map((name,index)=><label key={name} className={`chip-toggle ${days.includes(index)?'chip-toggle--on':''}`}><input type="checkbox" checked={days.includes(index)} onChange={()=>toggle(index)}/>{name}</label>)}</div></div><div className="field field--inline"><label htmlFor="optimisation-time">Optimisation time</label><select id="optimisation-time" className="input input--select" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}><option value={10}>Quick (10s)</option><option value={30}>Balanced (30s)</option><option value={60}>Thorough (60s)</option><option value={120}>Maximum (2 min)</option></select></div>{calendar&&<p className="form__note"><Badge>{days.length} days selected</Badge> {calendar.periods.filter(p=>p.is_teaching).length} teaching periods per day.</p>}<button type="button" className="button button--primary" onClick={()=>void generate()} disabled={busy||!label.trim()||!days.length}>{busy?'Generating…':'Create and generate timetable'}</button></section>{job&&job.status!=='completed'&&<section className="card section"><h2 className="section__title">Generation {job.status}</h2><p>{job.progress}% · {job.stage}</p>{job.message&&<Alert tone="error" title="Generation failed">{job.message}</Alert>}</section>}</>
}
