import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, LoadingBlock } from '../components/States'
import { useToast } from '../components/Toast'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Calendar, type Job, type TimetableType } from '../lib/scheduling'

const RUNNING = new Set(['queued','running','optimizing','validating'])
export function GeneratePage(){
 const {notify}=useToast(); const [calendar,setCalendar]=useState<Calendar|null>(null); const [types,setTypes]=useState<TimetableType[]>([]); const [typeId,setTypeId]=useState<number|null>(null); const [days,setDays]=useState<number[]>([]); const [labels,setLabels]=useState<Record<number,string>>({}); const [periods,setPeriods]=useState<number[]>([]); const [job,setJob]=useState<Job|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [starting,setStarting]=useState(false)
 async function load(){setLoading(true);setError(null);try{const [cal,tt]=await Promise.all([scheduling.calendar(),scheduling.timetableTypes()]);setCalendar(cal);setTypes(tt);setLabels(Object.fromEntries(cal.days.map(d=>[d.index,d.name])));if(tt[0]){setTypeId(tt[0].id);setDays(tt[0].day_indexes);setPeriods(cal.periods.filter(p=>p.is_teaching).map(p=>p.index))}}catch(e){setError(friendlyApiError(e,'load timetable configuration'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const configuredDays=useMemo(()=>calendar?.days.slice().sort((a,b)=>a.index-b.index)??[],[calendar]); const teachingPeriods=useMemo(()=>calendar?.periods.filter(p=>p.is_teaching).slice().sort((a,b)=>a.index-b.index)??[],[calendar]); const selectedType=types.find(t=>t.id===typeId); const running=!!job&&RUNNING.has(job.status)
 function toggle(list:number[],value:number,setter:(v:number[])=>void){setter(list.includes(value)?list.filter(v=>v!==value):[...list,value].sort((a,b)=>a-b))}
 function selectType(id:number){const t=types.find(x=>x.id===id);if(!t)return;setTypeId(id);setDays(t.day_indexes);setPeriods(teachingPeriods.map(p=>p.index))}
 async function generate(){if(!typeId||!days.length||!periods.length||running||starting)return;setStarting(true);try{const next=await scheduling.generateProfile({timetable_type_id:typeId,period_indexes:periods,day_indexes:days,day_names:Object.fromEntries(days.map(i=>[i,labels[i]||configuredDays.find(d=>d.index===i)?.name||String(i)])),max_seconds:30});setJob(next);notify('Timetable generation started.','success')}catch(e){notify(friendlyApiError(e,'generate timetable'),'error')}finally{setStarting(false)}}
 useEffect(()=>{if(!job||!running)return;const timer=window.setInterval(()=>void scheduling.job(job.id).then(setJob).catch(()=>undefined),900);return()=>window.clearInterval(timer)},[job?.id,job?.status,running])
 if(loading)return <><PageHeader title="Build a timetable" description="Create a timetable using an existing timetable type." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable',to:'/timetable'},{label:'Build a timetable'}]}/><div className="card section"><LoadingBlock label="Loading timetable configuration" rows={5}/></div></>
 if(error)return <><PageHeader title="Build a timetable" description="Create a timetable using an existing timetable type." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable',to:'/timetable'},{label:'Build a timetable'}]}/><Alert tone="error" title="Configuration unavailable">{error}</Alert></>
 return <><PageHeader title="Build a timetable" description="Create a timetable using an existing timetable type." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable',to:'/timetable'},{label:'Build a timetable'}]}/>
  {job&&<section className="card section"><div className="panel__head"><div><h2 className="section__title">Generation {running?'in progress':'result'}</h2><p className="form__note">{job.message||job.stage}</p></div><Badge tone={job.status==='completed'?'success':job.status==='failed'?'danger':'neutral'}>{job.status}</Badge></div><div className="progress" role="progressbar" aria-valuenow={job.progress} aria-valuemin={0} aria-valuemax={100}><div className="progress__bar" style={{width:`${job.progress}%`}}/></div></section>}
  <section className="card section"><div className="panel__head"><div><p className="form__note">TIMETABLE</p><h2 className="section__title">Build a timetable</h2><p className="form__note">Configure this timetable. Reusable timetable types are managed separately.</p></div><Badge tone="neutral">Draft</Badge></div>
   <div className="form form--grid">
    <div className="field form--grid__full"><label className="field__label">Timetable type</label><div className="form__row"><select className="input input--select" value={typeId??''} onChange={e=>selectType(Number(e.target.value))}><option value="">Select a timetable type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><a className="button button--ghost button--sm" href="/scheduling/timetable-types">Manage timetable types</a></div><p className="form__note">Choose an existing type for this timetable.</p></div>
    {selectedType&&<div className="field form--grid__full"><label className="field__label">Schedule days</label><div className="chip-toggles">{configuredDays.filter(d=>selectedType.day_indexes.includes(d.index)).map(d=><label key={d.index} className={`chip-toggle ${days.includes(d.index)?'chip-toggle--on':''}`}><input type="checkbox" checked={days.includes(d.index)} onChange={()=>toggle(days,d.index,setDays)}/><span>{labels[d.index]||d.name}</span></label>)}</div></div>}
    {selectedType&&<div className="field form--grid__full"><label className="field__label">Display labels</label><div className="form form--grid">{configuredDays.filter(d=>selectedType.day_indexes.includes(d.index)).map(d=><div className="field" key={d.index}><label className="field__label" htmlFor={`schedule-label-${d.index}`}>{d.name}</label><input id={`schedule-label-${d.index}`} type={selectedType.display_mode==='date'?'date':'text'} className="input" value={labels[d.index]??d.name} onChange={e=>setLabels(v=>({...v,[d.index]:e.target.value}))}/></div>)}</div></div>}
    <div className="field form--grid__full"><label className="field__label">Teaching periods</label><div className="chip-toggles">{teachingPeriods.map(p=><label key={p.index} className={`chip-toggle ${periods.includes(p.index)?'chip-toggle--on':''}`}><input type="checkbox" checked={periods.includes(p.index)} onChange={()=>toggle(periods,p.index,setPeriods)}/><span>{p.name} · {p.start_time}–{p.end_time}</span></label>)}</div>{!teachingPeriods.length&&<p className="form__note">No teaching periods are configured.</p>}</div>
   </div>
   <div className="form__row" style={{marginTop:20}}><button className="button button--primary" type="button" disabled={!typeId||!days.length||!periods.length||running||starting} onClick={()=>void generate()}>{starting?'Starting…':running?`Generating… ${job?.progress??0}%`:'Generate timetable'}</button></div>
  </section>
 </>
}
