import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Badge, EmptyState, ErrorState } from '../components/States'
import { DataTable, type Column } from '../components/DataTable'
import { LayersIcon } from '../components/icons'
import { api, friendlyApiError, type Grade, type Level } from '../lib/api'
import { useAsync } from '../lib/useAsync'

export function GradesPage(){
 const {data:levels,loading:levelsLoading,error:levelsError,reload:reloadLevels}=useAsync<Level[]>(api.levels,e=>friendlyApiError(e,'load levels'))
 const [levelId,setLevelId]=useState<number|null>(null); const [grades,setGrades]=useState<Grade[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Grade|null>(null); const [name,setName]=useState(''); const [code,setCode]=useState(''); const [order,setOrder]=useState('1'); const [active,setActive]=useState(true); const [saving,setSaving]=useState(false)
 const activeLevels=useMemo(()=>[...(levels||[])].filter(x=>x.status!==false).sort((a,b)=>a.display_order-b.display_order),[levels]); useEffect(()=>{if(levelId===null&&activeLevels.length)setLevelId(activeLevels[0].id)},[activeLevels,levelId])
 const load=useCallback(async()=>{if(levelId===null)return;setLoading(true);setError(null);try{setGrades(await api.grades(levelId))}catch(e){setError(friendlyApiError(e,'load grades'))}finally{setLoading(false)}},[levelId]); useEffect(()=>{void load()},[load])
 function openCreate(){setEditing(null);setName('');setCode('');setOrder('1');setActive(true);setShowForm(true)} function openEdit(g:Grade){setEditing(g);setName(g.name);setCode(g.code);setOrder(String(g.display_order));setActive(g.status!==false);setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();if(levelId===null||!name.trim()||!code.trim())return;setSaving(true);setError(null);try{if(editing)await api.updateGrade(editing.id,{name:name.trim(),code:code.trim(),display_order:Number(order)||1,status:active});else await api.createGrade({level_id:levelId,name:name.trim(),code:code.trim(),display_order:Number(order)||1,status:active});setShowForm(false);setEditing(null);await load()}catch(e){setError(friendlyApiError(e,'save grade'))}finally{setSaving(false)}}
 const columns:Column<Grade>[]=[{key:'name',header:'Grade',render:r=><strong>{r.name}</strong>},{key:'code',header:'Code',render:r=>r.code},{key:'order',header:'Order',render:r=>r.display_order},{key:'status',header:'Status',render:r=>r.status===false?<Badge tone="warning">Inactive</Badge>:<Badge tone="success">Active</Badge>},{key:'actions',header:'Actions',render:r=><button type="button" className="button button--ghost button--sm" onClick={()=>openEdit(r)}>Edit</button>}]
 return <><PageHeader title="Grades" description="Configure education years within each level, such as PP1, PP2, Grade 1, or Grade 7." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Grades'}]}/>{levelsError?<ErrorState title="Levels could not load" message={levelsError} onRetry={reloadLevels}/>:<><section className="card section"><div className="streams-toolbar"><div><label className="label" htmlFor="grade-level">Level</label><select id="grade-level" className="input" value={levelId??''} onChange={e=>setLevelId(Number(e.target.value))} disabled={levelsLoading||!activeLevels.length}>{!activeLevels.length&&<option value="">No levels configured</option>}{activeLevels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><button className="button button--primary" type="button" onClick={openCreate} disabled={levelId===null}>Create grade</button></div></section>{error&&<ErrorState title="Grades could not be updated" message={error} onRetry={load}/>}<section className="card section"><div className="section__header"><div><h2 className="section__title">Grades in {activeLevels.find(l=>l.id===levelId)?.name||'selected level'}</h2></div></div><DataTable caption="Grades" columns={columns} rows={grades} rowKey={r=>r.id} loading={loading} loadingLabel="Loading grades" empty={<EmptyState title="No grades configured" description="Create grades under the selected education level." icon={<LayersIcon width={22} height={22}/>}/>} /></section>{showForm&&<div className="streams-modal-backdrop"><div className="card streams-modal" role="dialog" aria-modal="true"><h2 className="section__title">{editing?'Edit grade':'Create grade'}</h2><p className="section__description">{activeLevels.find(l=>l.id===levelId)?.name}</p><form onSubmit={save}><label className="label" htmlFor="grade-name">Name</label><input id="grade-name" className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Grade 4" required/><label className="label" htmlFor="grade-code">Code</label><input id="grade-code" className="input" value={code} onChange={e=>setCode(e.target.value)} placeholder="G4" required/><label className="label" htmlFor="grade-order">Display order</label><input id="grade-order" className="input" type="number" min="1" value={order} onChange={e=>setOrder(e.target.value)} required/><label className="label"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active</label><div className="streams-modal__actions"><button type="button" className="button button--ghost" onClick={()=>setShowForm(false)}>Cancel</button><button type="submit" className="button button--primary" disabled={saving}>{saving?'Saving…':editing?'Save grade':'Create grade'}</button></div></form></div></div>}</>}</>
}
