import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, LoadingBlock } from '../components/States'
import { api, type AcademicYear, type Level, type SchoolClassSetup, type StudentListItem } from '../lib/api'
import { examinations, type ExamSubject, type Examination } from '../lib/examinations'
import { scheduling, type Teacher } from '../lib/scheduling'
import { friendlyApiError } from '../lib/api'

type Principal = { role?: string; teacher_id?: number | null }
const DOS_ROLES = new Set(['admin', 'scheduler', 'dos', 'director_of_studies', 'director-of-studies'])
type Option = [number | string, string]

export default function MarkAccessPage() {
  const [principal, setPrincipal] = useState<Principal | null>(null); const [exams, setExams] = useState<Examination[]>([]); const [years, setYears] = useState<AcademicYear[]>([]); const [levels, setLevels] = useState<Level[]>([]); const [classes, setClasses] = useState<SchoolClassSetup[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [subjects, setSubjects] = useState<{ id:number; name:string }[]>([]); const [assignments, setAssignments] = useState<ExamSubject[]>([]); const [students, setStudents] = useState<StudentListItem[]>([]); const [entries, setEntries] = useState<Record<number,{score:string;remarks:string}>>({})
  const [examId,setExamId]=useState(''); const [yearId,setYearId]=useState(''); const [levelId,setLevelId]=useState(''); const [classId,setClassId]=useState(''); const [subjectId,setSubjectId]=useState(''); const [assignmentTeacherId,setAssignmentTeacherId]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null)
  const isDos=DOS_ROLES.has(String(principal?.role??'').trim().toLowerCase()); const selectedExam=exams.find(x=>x.id===Number(examId)); const selectedAssignment=assignments.find(x=>x.subject_id===Number(subjectId)&&x.academic_year_id===Number(yearId)&&x.level_id===Number(levelId)&&x.school_class_id===Number(classId)); const examIsAnalyzed=selectedExam?.status==='published'||selectedExam?.status==='locked'; const teacherIsAssigned=Boolean(selectedAssignment&&principal?.role==='teacher'&&principal.teacher_id===selectedAssignment.teacher_id); const canUpload=Boolean(selectedAssignment&&!examIsAnalyzed&&(isDos||teacherIsAssigned))
  const visibleClasses=useMemo(()=>classes.filter(c=>(!yearId||c.academic_year_id===Number(yearId))&&(!levelId||c.level_id===Number(levelId))),[classes,yearId,levelId]); const visibleAssignments=useMemo(()=>assignments.filter(a=>(!yearId||a.academic_year_id===Number(yearId))&&(!levelId||a.level_id===Number(levelId))&&(!classId||a.school_class_id===Number(classId))),[assignments,yearId,levelId,classId])
  useEffect(()=>{void Promise.all([scheduling.me(),examinations.list(),api.academicYears(),api.levels(),api.schoolClasses(),scheduling.teachers(),scheduling.subjects()]).then(([me,e,y,l,c,t,s])=>{setPrincipal(me);setExams(e);setYears(y);setLevels(l);setClasses(c);setTeachers(t);setSubjects(s.map(x=>({id:x.id,name:x.name})));const cy=y.find(x=>x.is_current)??y[0];if(cy)setYearId(String(cy.id));if(e[0])setExamId(String(e[0].id))}).catch(err=>setError(friendlyApiError(err,'load mark access'))).finally(()=>setLoading(false))},[])
  useEffect(()=>{setClassId(current=>visibleClasses.some(c=>String(c.id)===current)?current:'')},[visibleClasses])
  useEffect(()=>{if(!selectedExam){setAssignments([]);return}void examinations.listSubjects(selectedExam.id).then(setAssignments).catch(err=>setError(friendlyApiError(err,'load subject assignments')))},[selectedExam])
  useEffect(()=>{if(!classId){setStudents([]);return}void apiFetch<{items:StudentListItem[]}>(`/api/v1/students?academic_year_id=${yearId}&class_id=${classId}&page=1&page_size=100`).then(response=>setStudents(response.items??[])).catch(()=>setStudents([]))},[classId,yearId])
  useEffect(()=>{if(!selectedExam||!selectedAssignment){setEntries({});return}void examinations.listEntries(selectedExam.id,selectedAssignment.subject_id).then(rows=>{const next:Record<number,{score:string;remarks:string}>={};rows.forEach(row=>{next[row.student_id]={score:row.score==null?'':String(row.score),remarks:row.remarks??''}});setEntries(next)}).catch(err=>setError(friendlyApiError(err,'load marks')))},[selectedExam,selectedAssignment])
  useEffect(()=>{const a=visibleAssignments.find(x=>x.subject_id===Number(subjectId)&&x.school_class_id===Number(classId));setAssignmentTeacherId(a?.teacher_id?String(a.teacher_id):'')},[visibleAssignments,subjectId,classId])
  async function assignTeacher(){if(!selectedExam||!yearId||!levelId||!classId||!subjectId)return;setBusy(true);setMessage(null);try{const existing=assignments.find(x=>x.exam_id===selectedExam.id&&x.subject_id===Number(subjectId)&&x.academic_year_id===Number(yearId)&&x.level_id===Number(levelId)&&x.school_class_id===Number(classId));const payload={subject_id:Number(subjectId),academic_year_id:Number(yearId),level_id:Number(levelId),school_class_id:Number(classId),teacher_id:assignmentTeacherId?Number(assignmentTeacherId):null,total_marks:existing?.total_marks??selectedExam.total_marks};if(existing)await examinations.updateSubject(selectedExam.id,existing.id,payload);else await examinations.assignSubject(selectedExam.id,payload);setAssignments(await examinations.listSubjects(selectedExam.id));setMessage('Teacher duty saved for the selected school class and subject.')}catch(err){setMessage(friendlyApiError(err,'save teacher assignment'))}finally{setBusy(false)}}
  async function saveMarks(){if(!selectedExam||!selectedAssignment||!canUpload)return;setBusy(true);setMessage(null);try{const payload=students.filter(s=>entries[s.id]?.score!=='').map(s=>({student_id:s.id,subject_id:selectedAssignment.subject_id,score:Number(entries[s.id].score),remarks:entries[s.id].remarks||null}));const result=await examinations.enterScores(selectedExam.id,payload);setMessage(`Saved ${result.created+result.updated} marks.`)}catch(err){setMessage(friendlyApiError(err,'save marks'))}finally{setBusy(false)}}
  if(loading)return <LoadingBlock label="Loading mark access" rows={7}/>
  return <div><PageHeader title="Mark Entry & Teacher Duties" description="DOS assigns a teacher to an exact examination, academic year, level and canonical school class. The assigned teacher enters marks for that duty." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Examinations',to:'/examinations'},{label:'Mark Entry · Assign Teachers'}]}/>{error&&<Alert tone="error">{error}</Alert>}{message&&<Alert tone="info">{message}</Alert>}
    <section className="card section"><h2 className="section__title">1. Examination context</h2><div className="form form--grid"><Select label="Examination" value={examId} options={exams.map(x=>[x.id,x.name])} onChange={setExamId}/><Select label="Academic year" value={yearId} options={years.map(x=>[x.id,x.name])} onChange={v=>{setYearId(v);setClassId('')}}/><Select label="Level" value={levelId} options={levels.map(x=>[x.id,x.name])} onChange={v=>{setLevelId(v);setClassId('')}}/><Select label="School class" value={classId} options={visibleClasses.map(x=>[x.id,`${x.name} · ${x.code}`])} onChange={setClassId}/><Select label="Subject" value={subjectId} options={visibleAssignments.map(x=>[x.subject_id,subjects.find(s=>s.id===x.subject_id)?.name??`Subject ${x.subject_id}`])} onChange={setSubjectId}/></div>{selectedExam&&<p style={{color:'var(--color-ink-muted)',fontSize:'.85rem'}}>Examination status: <strong>{selectedExam.status}</strong>.</p>}</section>
    {isDos&&!examIsAnalyzed&&selectedExam&&classId&&subjectId&&<section className="card section"><h2 className="section__title">2. Assign teacher duty</h2><div className="form form--grid"><Select label="Teacher" value={assignmentTeacherId} options={teachers.map(x=>[x.id,x.name])} onChange={setAssignmentTeacherId}/></div><button className="button button--primary" disabled={busy} onClick={assignTeacher}>{busy?'Saving…':selectedAssignment?'Update Teacher Duty':'Assign Teacher Duty'}</button></section>}
    {selectedAssignment&&<section className="card section"><h2 className="section__title">3. Duty status</h2><div style={{display:'flex',gap:'var(--space-2)',flexWrap:'wrap'}}><Badge tone="info">School class: #{selectedAssignment.school_class_id}</Badge><Badge tone="info">Teacher: {selectedAssignment.teacher_id??'Unassigned'}</Badge><Badge tone={canUpload?'success':'info'}>{canUpload?'Mark entry enabled':'View only'}</Badge><Badge tone="info">Maximum: {selectedAssignment.total_marks}</Badge></div></section>}
    {classId&&subjectId&&<section className="card section"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}><div><h2 className="section__title">{canUpload?'4. Enter marks':'4. View marks'}</h2><p style={{color:'var(--color-ink-muted)',margin:0}}>{subjects.find(x=>x.id===Number(subjectId))?.name??'Subject'} · {classes.find(x=>x.id===Number(classId))?.name??'School class'}</p></div></div>{!selectedAssignment?<EmptyState title="No subject assignment" description="Assign this subject to the selected school class before entering marks."/>:<><div style={{overflowX:'auto',marginTop:'var(--space-3)'}}><table style={{width:'100%'}}><thead><tr><th>Learner</th><th>Admission No.</th><th>Score / {selectedAssignment.total_marks}</th><th>Remarks</th></tr></thead><tbody>{students.map(student=><tr key={student.id}><td>{[student.first_name,student.middle_name,student.last_name].filter(Boolean).join(' ')}</td><td>{student.admission_number}</td><td><input className="input" style={{minWidth:'7rem'}} type="number" min="0" max={selectedAssignment.total_marks} disabled={!canUpload} value={entries[student.id]?.score??''} onChange={e=>setEntries(cur=>({...cur,[student.id]:{score:e.target.value,remarks:cur[student.id]?.remarks??''}}))}/></td><td><input className="input" disabled={!canUpload} value={entries[student.id]?.remarks??''} onChange={e=>setEntries(cur=>({...cur,[student.id]:{score:cur[student.id]?.score??'',remarks:e.target.value}}))}/></td></tr>)}</tbody></table></div><button className="button button--primary" disabled={busy||!canUpload||!students.length} onClick={saveMarks}>{busy?'Saving…':'Save marks'}</button></>}</section>}
  </div>
}
function Select({label,value,options,onChange}:{label:string;value:string;options:Option[];onChange:(value:string)=>void}){return <label className="field"><span className="field__label">{label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select {label.toLowerCase()}</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
