import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, ErrorState, LoadingBlock } from '../components/States'
import { PublishedTimetableGridWithEvents } from '../components/PublishedTimetableGridWithEvents'
import { CalendarIcon } from '../components/icons'
import { friendlyApiError } from '../lib/api'
import { cachedFetch, formatSavedAt } from '../lib/offline'
import { Link } from '../lib/router'
import { scheduling, type Calendar, type Event, type SchoolClass, type Teacher, type TimetableView } from '../lib/scheduling'

type Scope = 'class' | 'teacher'
type SubjectOption = { id: number; name: string; code?: string; colour?: string }

function canReviewGeneratedDraft(role?: string) { const order = ['viewer', 'student', 'teacher', 'scheduler', 'admin', 'super_admin']; const index = order.indexOf(String(role ?? '').toLowerCase()); return index >= order.indexOf('scheduler') }
function validSubjectColour(value: string | undefined) { return value && /^#[0-9A-Fa-f]{6}$/.test(value) ? value : undefined }

function buildView(calendar: Calendar, version: NonNullable<TimetableView['version']>, lessons: Array<{ day_index: number; period_index: number; subject_id: number; teacher_id: number; class_id: number }>, subjects: SubjectOption[], teachers: Array<{ id: number; name: string; code?: string; staff_number?: string }>, classes: Array<{ id: number; name: string; code?: string }>, scope: Scope, targetId: number): TimetableView {
  const subjectCode = new Map<number, string>(subjects.map((item): [number, string] => [item.id, item.code?.trim() || item.name]))
  const subjectColour = new Map<number, string | undefined>(subjects.map((item): [number, string | undefined] => [item.id, validSubjectColour(item.colour)]))
  const teacherCode = new Map<number, string>(teachers.map((item): [number, string] => [item.id, item.code?.trim() || item.staff_number?.trim() || item.name]))
  const classCode = new Map<number, string>(classes.map((item): [number, string] => [item.id, item.code?.trim() || item.name]))
  const target = scope === 'teacher' ? teachers.find((item) => item.id === targetId)?.name : classes.find((item) => item.id === targetId)?.name
  return { version, target_name: target, days: calendar.days.filter((day) => day.is_active).map((day) => ({ index: day.index, name: day.name })), periods: calendar.periods.map((period) => ({ index: period.index, name: period.name, start_time: period.start_time, end_time: period.end_time, is_teaching: period.is_teaching })), lessons: lessons.map((lesson) => ({ day: lesson.day_index, period: lesson.period_index, subject: subjectCode.get(lesson.subject_id) ?? 'Unknown subject', subject_colour: subjectColour.get(lesson.subject_id), teacher: teacherCode.get(lesson.teacher_id) ?? null, class: classCode.get(lesson.class_id) ?? 'Unknown class' })) }
}

function normalisePublishedView(view: TimetableView, subjects: SubjectOption[], teachers: Teacher[], classes: SchoolClass[]): TimetableView {
  const subjectByName = new Map<string, SubjectOption>(subjects.map((item): [string, SubjectOption] => [item.name.trim().toLowerCase(), item]))
  const subjectByCode = new Map<string, SubjectOption>(subjects.filter((item) => Boolean(item.code?.trim())).map((item): [string, SubjectOption] => [item.code!.trim().toLowerCase(), item]))
  const teacherByName = new Map<string, string>(teachers.map((item): [string, string] => [item.name.trim().toLowerCase(), item.code?.trim() || item.staff_number?.trim() || item.name]))
  const teacherByCode = new Set(teachers.flatMap((item) => [item.code?.trim(), item.staff_number?.trim()]).filter(Boolean))
  const classByName = new Map<string, string>(classes.map((item): [string, string] => [item.name.trim().toLowerCase(), item.code?.trim() || item.name]))
  const classByCode = new Set(classes.map((item) => item.code?.trim()).filter(Boolean))
  return { ...view, lessons: view.lessons.map((lesson) => { const rawSubject = lesson.subject?.trim() ?? ''; const subject = subjectByCode.get(rawSubject.toLowerCase()) ?? subjectByName.get(rawSubject.toLowerCase()); return { ...lesson, subject: subject?.code?.trim() || subject?.name || lesson.subject, subject_colour: validSubjectColour(subject?.colour) ?? validSubjectColour(lesson.subject_colour), teacher: lesson.teacher ? (teacherByCode.has(lesson.teacher.trim()) ? lesson.teacher.trim() : teacherByName.get(lesson.teacher.trim().toLowerCase()) ?? lesson.teacher) : null, class: classByCode.has(lesson.class.trim()) ? lesson.class.trim() : classByName.get(lesson.class.trim().toLowerCase()) ?? lesson.class } }) }
}

export function MyTimetablePage() {
  const [scope, setScope] = useState<Scope>('teacher'); const [targetId, setTargetId] = useState<number | null>(null); const [teacherId, setTeacherId] = useState<number | null>(null); const [options, setOptions] = useState<{ classes: SchoolClass[]; teachers: Teacher[]; subjects: SubjectOption[] } | null>(null); const [view, setView] = useState<TimetableView | null>(null); const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [stale, setStale] = useState<number | null>(null); const [isTeacher, setIsTeacher] = useState(false); const [classTeacherClassId, setClassTeacherClassId] = useState<number | null>(null); const [canReviewDraft, setCanReviewDraft] = useState(false)
  useEffect(() => { let active = true; cachedFetch('mytt:options', async () => { const [classes, teachers, subjects, me] = await Promise.all([scheduling.classes(), scheduling.teachers(), scheduling.subjects(), scheduling.me()]); return { classes, teachers, subjects, me } }).then((result) => { if (!active) return; const { classes, teachers, subjects, me } = result.data; setOptions({ classes, teachers, subjects }); setCanReviewDraft(canReviewGeneratedDraft(me.role)); if (me.teacher_id) { setIsTeacher(true); setTeacherId(me.teacher_id); const assignedClass = classes.find((item) => item.class_teacher_id === me.teacher_id); setClassTeacherClassId(assignedClass?.id ?? null); setScope('teacher'); setTargetId(me.teacher_id) } else if (me.class_id) { setScope('class'); setTargetId(me.class_id) } else { setScope('class'); setTargetId(classes[0]?.id ?? null) } }).catch(() => { if (active) setError('Could not load your school data.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  useEffect(() => { if (!targetId || !options) return; let active = true; setLoading(true); setError(null); const load = async () => { if (!canReviewDraft) { const [result, eventRows] = await Promise.all([cachedFetch(`mytt:${scope}:${targetId}`, () => scheduling.view(scope, targetId)), scheduling.events()]); return { view: normalisePublishedView(result.data, options.subjects, options.teachers, options.classes), events: eventRows, savedAt: result.stale ? result.savedAt : null } } const [calendar, versions, subjects, teachers, classes, eventRows] = await Promise.all([scheduling.calendar(), scheduling.versions(), scheduling.subjects(), scheduling.teachers(), scheduling.classes(), scheduling.events()]); const version = [...versions].sort((a, b) => (b.number ?? b.id) - (a.number ?? a.id))[0]; if (!version) return { view: null, events: eventRows, savedAt: null }; const allLessons = await scheduling.lessons(version.id); const lessons = allLessons.filter((lesson) => scope === 'teacher' ? lesson.teacher_id === targetId : lesson.class_id === targetId); return { view: buildView(calendar, version, lessons, subjects, teachers, classes, scope, targetId), events: eventRows, savedAt: null } }; load().then((result) => { if (!active) return; setView(result.view); setEvents(result.events); setStale(result.savedAt) }).catch((err) => { if (active) setError(friendlyApiError(err, 'load the timetable')) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [scope, targetId, canReviewDraft, options])
  const targets = scope === 'class' ? (options?.classes ?? []) : (options?.teachers ?? []); const isDraft = view?.version?.status === 'draft'; const canViewAssignedClass = isTeacher && classTeacherClassId !== null
  if (loading && !view) return <><PageHeader title="My timetable" description="Your current timetable." /><div className="card section"><LoadingBlock label="Loading your timetable" rows={6} /></div></>
  if (error && !view) return <><PageHeader title="My timetable" /><ErrorState title="Timetable could not load" message={error} /></>
  return <><PageHeader title={scope === 'teacher' ? `Teacher: ${view?.target_name ?? ''}` : `Class: ${view?.target_name ?? ''}`} description={scope === 'teacher' ? 'Your teaching timetable.' : 'Timetable for your assigned class.'} breadcrumbs={[{ label: 'Dashboard', to: '/' }, { label: 'My timetable' }]} actions={view?.version && canReviewDraft && isDraft ? <Link className="button button--secondary button--sm" to={`/timetable?version=${view.version.id}`}>Edit timetable</Link> : undefined} />{stale && <Alert tone="info" title="Offline copy">Saved on this device {formatSavedAt(stale)}. It will refresh when you reconnect.</Alert>}{view?.version && <section className="card section"><div className="toolbar"><div><h2 className="section__title">Timetable</h2><p className="section__description">Version {view.version.number ?? view.version.id}</p></div><Badge tone={isDraft ? 'neutral' : 'success'}>{isDraft ? 'Draft' : 'Published'}</Badge></div></section>}<section className="card section"><div className="toolbar"><div className="field field--inline"><label className="field__label" htmlFor="my-scope">Show</label><select id="my-scope" className="input input--select" value={scope} onChange={(event) => { const next = event.target.value as Scope; if (isTeacher) { if (next === 'class' && classTeacherClassId !== null) { setScope('class'); setTargetId(classTeacherClassId) } else { setScope('teacher'); setTargetId(teacherId) } return } setScope(next); setTargetId(next === 'class' ? (options?.classes[0]?.id ?? null) : (options?.teachers[0]?.id ?? null)) }}><option value="teacher">My teacher timetable</option>{canViewAssignedClass && <option value="class">My assigned class timetable</option>}{!isTeacher && <option value="class">A class timetable</option>}{!isTeacher && <option value="teacher">A teacher timetable</option>}</select></div>{!isTeacher && <div className="field field--inline"><label className="field__label" htmlFor="my-target">{scope === 'class' ? 'Class' : 'Teacher'}</label><select id="my-target" className="input input--select" value={targetId ?? ''} onChange={(event) => setTargetId(Number(event.target.value))}>{targets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>}{isTeacher && scope === 'class' && canViewAssignedClass && <div className="field field--inline"><label className="field__label">Assigned class</label><div className="input">{options?.classes.find((item) => item.id === classTeacherClassId)?.name ?? 'Assigned class'}</div></div>}</div></section>{view?.version ? <section className="card section"><PublishedTimetableGridWithEvents view={view} mode={scope} events={events} /></section> : <section className="card section"><EmptyState title="No timetable generated yet" description="Generate a timetable first. Once generated, it will appear here for review." icon={<CalendarIcon width={22} height={22} />} /></section>}</>
}
