import { useCallback, useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, ErrorState, LoadingBlock } from '../components/States'
import { useToast } from '../components/Toast'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Day, type Period } from '../lib/scheduling'

const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
function addMinutes(time: string, minutes: number) { const [h,m]=time.split(':').map(Number); const total=h*60+m+minutes; return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}` }
function makeDays(count:number): Omit<Day,'id'>[] { return Array.from({length:count},(_,index)=>({index,name:WEEKDAYS[index] ?? `Day ${index+1}`,short_form:WEEKDAYS[index]?.slice(0,3) ?? `D${index+1}`,date_value:null,is_active:true})) }
function makePeriods(count:number): Omit<Period,'id'>[] { const rows:Omit<Period,'id'>[]=[]; let start='08:20'; for(let i=0;i<count;i++){const end=addMinutes(start,40); rows.push({index:i,name:`Period ${i+1}`,short_form:`P${i+1}`,start_time:start,end_time:end,is_teaching:true}); start=end} return rows }
export function PeriodsPage() {
  const { notify } = useToast(); const [days,setDays]=useState<Omit<Day,'id'>[]>([]); const [periods,setPeriods]=useState<Omit<Period,'id'>[]>([]); const [mode,setMode]=useState<'day'|'date'>('day'); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [locked,setLocked]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const c=await scheduling.calendar();setMode(c.display_mode==='date'?'date':'day');setDays(c.days.length?c.days.map(({index,name,short_form,date_value,is_active})=>({index,name,short_form:short_form??'',date_value:date_value??null,is_active})):makeDays(5));setPeriods(c.periods.length?c.periods.map(({index,name,short_form,start_time,end_time,is_teaching})=>({index,name,short_form:short_form??'',start_time,end_time,is_teaching})):makePeriods(8))}catch(e){setError(friendlyApiError(e,'load the school calendar'))}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const updateDay=(index:number,patch:Partial<Day>)=>setDays(current=>current.map(day=>day.index===index?{...day,...patch}:day))
  const updatePeriod=(index:number,patch:Partial<Period>)=>setPeriods(current=>current.map(period=>period.index===index?{...period,...patch}:period))
  const changeDayCount=(count:number)=>setDays(current=>Array.from({length:count},(_,i)=>current[i]??makeDays(count)[i]))
  const changePeriodCount=(count:number)=>setPeriods(current=>Array.from({length:count},(_,i)=>current[i]??makePeriods(count)[i]))
  const teachingCount=periods.filter(p=>p.is_teaching).length; const activeDays=days.filter(d=>d.is_active).length; const dayCount=days.length; const periodCount=periods.length
  const dateModeNote=useMemo(()=>mode==='date'?'Enter dates in the style you prefer, for example 31/8, 31-8, 31.8, 31/8/2026 or 31-8-2026.':'Use named days only. Dates are not shown in Days mode.',[mode])
  async function save(){if(saving)return;setSaving(true);setLocked(false);try{await scheduling.saveCalendar({days:mode==='date'?days:days.map(d=>({...d,date_value:null})),periods,display_mode:mode});notify('Calendar and periods saved.','success');await load()}catch(e){const message=friendlyApiError(e,'save the school calendar');if(String((e as {message?:string}).message??'').includes('Existing timetable lessons'))setLocked(true);else notify(message,'error')}finally{setSaving(false)}}
  return <><PageHeader title="Working days and periods" description="Configure either named days or editable dates, and define the numbered lesson periods used by the timetable." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Setup'},{label:'Periods'}]}/>{error?<ErrorState title="School calendar could not load" message={error} onRetry={load}/>:loading?<div className="card section"><LoadingBlock label="Loading the school calendar" rows={5}/></div>:<>
    {locked&&<Alert tone="error" title="Timetable structure is locked">Existing timetable lessons keep their day and period indexes. Rename labels without changing the configured slots.</Alert>}
    <section className="card section"><div className="panel__head"><h2 className="section__title">Calendar</h2><Badge>{mode==='date'?'Dates':'Days'}</Badge></div>
      <div className="form__row"><div className="field"><label>Calendar type</label><select className="input" value={mode} onChange={e=>setMode(e.target.value as 'day'|'date')}><option value="day">Days</option><option value="date">Dates</option></select></div><div className="field"><label>{mode==='date'?'Number of dates':'Number of days'}</label><select className="input" value={dayCount} onChange={e=>changeDayCount(Number(e.target.value))}>{Array.from({length:31},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></div></div>
      <p className="form__note">{dateModeNote}</p>
      <ul className="period-list">{days.map(day=><li className="period-row" key={day.index}><strong className="period-row__index">{day.index+1}</strong>{mode==='day'?<><input className="input period-row__name" aria-label={`Day ${day.index+1} name`} value={day.name} onChange={e=>updateDay(day.index,{name:e.target.value})}/><input className="input" aria-label={`Day ${day.index+1} short form`} placeholder="Short form" value={day.short_form} onChange={e=>updateDay(day.index,{short_form:e.target.value})}/></>:<><input className="input period-row__name" aria-label={`Date ${day.index+1}`} placeholder="31/8 or 31-8-2026" value={day.date_value??day.name} onChange={e=>updateDay(day.index,{date_value:e.target.value,name:e.target.value})}/><input className="input" aria-label={`Date ${day.index+1} short form`} placeholder="Short form" value={day.short_form} onChange={e=>updateDay(day.index,{short_form:e.target.value})}/></>}<label className="checkbox"><input type="checkbox" checked={day.is_active} onChange={()=>updateDay(day.index,{is_active:!day.is_active})}/>Active</label></li>)}</ul>
    </section>
    <section className="card section"><div className="panel__head"><h2 className="section__title">Periods</h2><Badge>{teachingCount} teaching periods</Badge></div>
      <div className="field"><label>Periods per day</label><select className="input" value={periodCount} onChange={e=>changePeriodCount(Number(e.target.value))}>{Array.from({length:30},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></div>
      <p className="form__note">Periods are numbered sequentially. Lessons are allocated elsewhere; this page only defines the period slots and their times.</p>
      <ul className="period-list">{periods.map(period=><li className={`period-row ${period.is_teaching?'':'period-row--break'}`} key={period.index}><strong className="period-row__index">Period {period.index+1}</strong><input className="input period-row__name" aria-label={`Period ${period.index+1} name`} value={period.name} onChange={e=>updatePeriod(period.index,{name:e.target.value})}/><input className="input" aria-label={`Period ${period.index+1} short form`} placeholder="Short form" value={period.short_form} onChange={e=>updatePeriod(period.index,{short_form:e.target.value})}/><input aria-label="Start time" className="input period-row__time" type="time" value={period.start_time} onChange={e=>updatePeriod(period.index,{start_time:e.target.value})}/><input aria-label="End time" className="input period-row__time" type="time" value={period.end_time} onChange={e=>updatePeriod(period.index,{end_time:e.target.value})}/><label className="checkbox"><input type="checkbox" checked={period.is_teaching} onChange={e=>updatePeriod(period.index,{is_teaching:e.target.checked})}/>Teaching</label></li>)}</ul>
    </section><div className="form__row"><button type="button" className="button button--primary" onClick={save} disabled={saving||periods.length===0||activeDays===0}>{saving?'Saving…':'Save calendar and periods'}</button></div>
  </>}</>
}
