import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { useToast } from '../components/Toast'
import { timetableProjects, type TimetableProject } from '../lib/timetableProjects'
import { scheduling, type Lesson, type Teacher, type Subject, type Room, type SchoolClass } from '../lib/scheduling'
export function ProjectTimetablePage(){
 const {notify}=useToast(); const [project,setProject]=useState<TimetableProject|null>(null); const [lessons,setLessons]=useState<Lesson[]>([]); const [teachers,setTeachers]=useState<Teacher[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [rooms,setRooms]=useState<Room[]>([]); const [classes,setClasses]=useState<SchoolClass[]>([]); const [busy,setBusy]=useState(false)
 const projectId=Number(new URLSearchParams(window.location.search).get('project_id')||0)
 const load=async()=>{if(!projectId)return;try{const [p,v,ts,ss,rs,cs]=await Promise.all([timetableProjects.list().then(xs=>xs.find(x=>x.id===projectId)||null),timetableProjects.current(projectId),scheduling.teachers(),scheduling.subjects(),scheduling.rooms(),scheduling.classes()]);setProject(p);setTeachers(ts);setSubjects(ss);setRooms(rs);setClasses(cs);setLessons(v?await scheduling.lessons(v.id):[])}catch(e){notify(e instanceof Error?e.message:'Could not load timetable project','error')}}
 useEffect(()=>{void load()},[])
 const generate=async()=>{if(!project)return;setBusy(true);try{await timetableProjects.generate(project.id,{label:project.name});notify('Generation started.','success');setTimeout(()=>void load(),1500)}catch(e){notify(e instanceof Error?e.message:'Could not generate timetable','error')}finally{setBusy(false)}}
 const teacher=new Map(teachers.map(x=>[x.id,x.name])); const subject=new Map(subjects.map(x=>[x.id,x.name])); const room=new Map(rooms.map(x=>[x.id,x.name])); const klass=new Map(classes.map(x=>[x.id,x.name]));
 if(!project)return <><PageHeader title="Timetable Project" description="Loading project…"/><div className="card section">No project selected or the project could not be found.</div></>
 return <><PageHeader title={project.name} description="Independent timetable project using shared school resources." breadcrumbs={[{label:'Timetable Projects',to:'/timetable-projects'},{label:project.name}]} actions={<button className="button button--primary button--sm" disabled={busy||project.status==='archived'} onClick={generate}>{busy?'Starting…':'Generate timetable'}</button>}/><div className="card section"><div className="form-grid"><div><strong>Status</strong><div>{project.status}</div></div><div><strong>Shared resources</strong><div>{teachers.length} teachers · {classes.length} classes · {rooms.length} rooms · {subjects.length} subjects</div></div><div><strong>Scheduled lessons</strong><div>{lessons.length}</div></div></div></div><div className="card section"><h2 className="section__title">Current timetable</h2>{lessons.length===0?<p>No timetable has been generated for this project yet.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Day</th><th>Period</th><th>Class</th><th>Subject</th><th>Teacher</th><th>Room</th></tr></thead><tbody>{lessons.map(l=><tr key={l.id}><td>{l.day_index}</td><td>{l.period_index}</td><td>{klass.get(l.class_id)??l.class_id}</td><td>{subject.get(l.subject_id)??l.subject_id}</td><td>{l.teacher_id?teacher.get(l.teacher_id)??l.teacher_id:'—'}</td><td>{l.room_id?room.get(l.room_id)??l.room_id:'—'}</td></tr>)}</tbody></table></div>}</div></>
}
