import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, ErrorState } from '../components/States'
import { DataTable, type Column } from '../components/DataTable'
import { Field } from '../components/Field'
import { LayersIcon, SearchIcon, UserIcon } from '../components/icons'
import { useToast } from '../components/Toast'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Room, type Subject, type SubjectInput, type Teacher, type TeacherInput, type RoomInput, type SchoolClass, type SchoolClassInput } from '../lib/scheduling'

type Kind = 'teachers' | 'subjects' | 'classes' | 'rooms'
type Row = Teacher | Subject | SchoolClass | Room
const TITLES: Record<Kind, { title: string; description: string; singular: string }> = {
  teachers: { title: 'Teachers', description: 'Staff, their limits and when they are unavailable.', singular: 'teacher' },
  subjects: { title: 'Subjects', description: 'Subjects used when building the timetable.', singular: 'subject' },
  classes: { title: 'Classes', description: 'Teaching groups that cannot be in two places at once.', singular: 'class' },
  rooms: { title: 'Rooms', description: 'Rooms and specialist spaces treated as bookable resources.', singular: 'room' },
}

export function SetupPage({ kind }: { kind: Kind }) {
  const { notify } = useToast(); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Row | 'new' | null>(null); const [savingRowId, setSavingRowId] = useState<number | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const data = await (kind === 'teachers' ? scheduling.teachers() : kind === 'subjects' ? scheduling.subjects() : kind === 'classes' ? scheduling.classes() : scheduling.rooms()); setRows(data as Row[]) } catch (err) { setError(friendlyApiError(err, `load ${kind}`)) } finally { setLoading(false) } }, [kind])
  useEffect(() => { setQuery(''); setEditing(null); void load() }, [load])
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return term ? rows.filter(row => row.name.toLowerCase().includes(term) || (row.code ?? '').toLowerCase().includes(term)) : rows }, [rows, query])
  async function remove(row: Row) { try { await (kind === 'teachers' ? scheduling.deleteTeacher(row.id) : kind === 'subjects' ? scheduling.deleteSubject(row.id) : kind === 'classes' ? scheduling.deleteClass(row.id) : scheduling.deleteRoom(row.id)); notify(`${TITLES[kind].singular} removed.`, 'success'); await load() } catch (err) { notify(friendlyApiError(err, `remove the ${TITLES[kind].singular}`), 'error') } }
  async function saveSubject(row: Subject) { if (savingRowId !== null) return; setSavingRowId(row.id); try { await scheduling.updateSubject(row.id, { name: row.name, code: row.code, colour: row.colour, prefers_morning: row.prefers_morning, prefers_double: row.prefers_double, spread_across_week: row.spread_across_week, required_room_type: row.required_room_type }); notify(`${row.name} saved.`, 'success'); await load() } catch (err) { notify(friendlyApiError(err, 'save subject'), 'error') } finally { setSavingRowId(null) } }
  const columns = useMemo<Column<Row>[]>(() => { const base: Column<Row>[] = [{ key: 'name', header: 'Name', render: row => row.name }, { key: 'code', header: 'Code', render: row => row.code }]; if (kind === 'teachers') base.push({ key: 'dept', header: 'Department', render: row => (row as Teacher).department || '—' }, { key: 'max', header: 'Max/day', render: row => (row as Teacher).max_lessons_per_day }, { key: 'avail', header: 'Availability', render: row => { const blocked = Object.values((row as Teacher).unavailable ?? {}).flat().length; return blocked ? <Badge tone="warning">{blocked} blocked</Badge> : <Badge tone="success">Full week</Badge> } }); if (kind === 'subjects') base.push({ key: 'color', header: 'Color', render: row => <span className="subject-color" style={{ backgroundColor: (row as Subject).colour }} aria-label={`Subject color ${(row as Subject).colour}`} /> }); if (kind === 'classes') base.push({ key: 'grade', header: 'Grade', render: row => (row as SchoolClass).grade || '—' }, { key: 'size', header: 'Students', render: row => (row as SchoolClass).student_count }); if (kind === 'rooms') base.push({ key: 'type', header: 'Type', render: row => (row as Room).room_type }, { key: 'cap', header: 'Capacity', render: row => (row as Room).capacity }, { key: 'building', header: 'Building', render: row => (row as Room).building || '—' }); return base }, [kind])
  const info = TITLES[kind]
  return <><PageHeader title={info.title} description={info.description} breadcrumbs={[{ label: 'Dashboard', to: '/' }, { label: 'Setup' }, { label: info.title }]} actions={<button type="button" className="button button--primary button--sm" onClick={() => setEditing('new')}>Add {info.singular}</button>} />{editing && <ResourceForm kind={kind} initial={editing === 'new' ? null : editing} onCancel={() => setEditing(null)} onSaved={async () => { setEditing(null); await load() }} />}{error ? <ErrorState title={`${info.title} could not load`} message={error} onRetry={load} /> : <section className="card section"><div className="toolbar"><div className="search"><SearchIcon className="search__icon" width={18} height={18} /><label className="visually-hidden" htmlFor="setup-search">Search {info.title.toLowerCase()}</label><input id="setup-search" className="input input--search" type="search" placeholder="Search by name or code" value={query} onChange={event => setQuery(event.target.value)} /></div>{query && <button type="button" className="button button--ghost button--sm" onClick={() => setQuery('')}>Clear search</button>}{!loading && <span className="toolbar__count">{filtered.length} of {rows.length}</span>}</div><DataTable caption={info.title} columns={columns} rows={filtered} rowKey={row => row.id} loading={loading} loadingLabel={`Loading ${info.title.toLowerCase()}`} empty={<EmptyState title={query ? `No matching ${info.title.toLowerCase()}` : `No ${info.title.toLowerCase()} yet`} description={query ? 'Nothing matches your search. Clear it to see everything.' : `Add your first ${info.singular} to start building the timetable.`} icon={kind === 'teachers' ? <UserIcon width={22} height={22} /> : <LayersIcon width={22} height={22} />} action={!query ? <button type="button" className="button button--primary button--sm" onClick={() => setEditing('new')}>Add {info.singular}</button> : undefined} />} rowActions={row => <>{kind === 'subjects' && <button type="button" className="button button--primary button--sm" disabled={savingRowId !== null} onClick={() => void saveSubject(row as Subject)}>{savingRowId === row.id ? 'Saving…' : 'Save'}</button>}<button type="button" className="button button--ghost button--sm" onClick={() => setEditing(row)}>Edit</button><button type="button" className="button button--ghost button--sm" onClick={() => remove(row)}>Delete</button></>} /></section>}</>
}

function SubjectForm({ initial, onCancel, onSaved }: { initial: Subject | null; onCancel: () => void; onSaved: () => void }) {
  const { notify } = useToast(); const [rooms, setRooms] = useState<Room[]>([]); const [roomId, setRoomId] = useState(''); const [values, setValues] = useState({ name: initial?.name ?? '', code: initial?.code ?? '', colour: initial?.colour ?? '#0F2A47' }); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null)
  useEffect(() => { void scheduling.rooms().then(setRooms).catch(err => setFormError(friendlyApiError(err, 'load rooms'))); if (initial) { void scheduling.requirements().then(items => { const existing = items.find((item: any) => item.subject_id === initial.id); setRoomId(existing?.room_id ? String(existing.room_id) : '') }).catch(() => undefined) } }, [initial])
  const set = (key: keyof typeof values, value: string) => setValues(current => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; if (!values.name.trim() || !values.code.trim()) { setFormError('Enter the subject name and code.'); return } setSaving(true); setFormError(null); try { const payload: SubjectInput = { name: values.name.trim(), code: values.code.trim(), colour: values.colour, prefers_morning: initial?.prefers_morning ?? false, prefers_double: initial?.prefers_double ?? false, spread_across_week: initial?.spread_across_week ?? true, required_room_type: initial?.required_room_type ?? null }; const subject = initial ? await scheduling.updateSubject(initial.id, payload) : await scheduling.createSubject(payload); if (roomId && subject.id) { const requirements = await scheduling.requirements(); const existing = requirements.find((item: any) => item.subject_id === subject.id); if (existing) await scheduling.updateRequirement(existing.id, { room_id: Number(roomId) } as any) } notify(initial ? 'Subject saved.' : 'Subject added.', 'success'); onSaved() } catch (err) { setFormError(friendlyApiError(err, 'save subject')) } finally { setSaving(false) } }
  return <section className="card section"><h2 className="section__title">{initial ? `Edit ${initial.name}` : 'New subject'}</h2>{formError && <Alert tone="error">{formError}</Alert>}<form className="form form--grid subject-simple-form" onSubmit={submit} noValidate><Field label="Subject name" required value={values.name} onChange={event => set('name', event.target.value)} /><Field label="Code" required value={values.code} onChange={event => set('code', event.target.value)} /><div className="field"><label className="field__label" htmlFor="subject-colour">Color</label><div className="subject-color-input"><input id="subject-colour" type="color" value={values.colour} onChange={event => set('colour', event.target.value)} /><input className="input" value={values.colour} onChange={event => set('colour', event.target.value)} aria-label="Color hex value" /></div></div><div className="field"><label className="field__label" htmlFor="subject-room">Room <span className="field__hint">optional</span></label><select id="subject-room" className="input" value={roomId} onChange={event => setRoomId(event.target.value)}><option value="">No preferred room</option>{rooms.map(room => <option key={room.id} value={room.id}>{room.name}{room.code ? ` (${room.code})` : ''}</option>)}</select></div><div className="form__row form--grid__full"><button className="button button--primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button><button className="button button--secondary" type="button" onClick={onCancel}>Cancel</button></div></form></section>
}

function ResourceForm({ kind, initial, onCancel, onSaved }: { kind: Kind; initial: Row | null; onCancel: () => void; onSaved: () => void }) { return kind === 'subjects' ? <SubjectForm initial={initial as Subject | null} onCancel={onCancel} onSaved={onSaved} /> : <GeneralResourceForm kind={kind} initial={initial} onCancel={onCancel} onSaved={onSaved} /> }

function GeneralResourceForm({ kind, initial, onCancel, onSaved }: { kind: Exclude<Kind, 'subjects'>; initial: Row | null; onCancel: () => void; onSaved: () => void }) {
  const { notify } = useToast(); const [values, setValues] = useState<Record<string, unknown>>(() => defaults(kind, initial)); const [errors, setErrors] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null); const set = (key: string, value: unknown) => setValues(current => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; const next: Record<string, string> = {}; if (!String(values.name ?? '').trim()) next.name = 'Enter a name.'; if (!String(values.code ?? '').trim()) next.code = 'Enter a short code.'; if (kind === 'classes') { const count = Number(values.student_count); if (!Number.isInteger(count) || count < 1 || count > 500) next.student_count = 'Enter a whole number of students from 1 to 500.' } setErrors(next); setFormError(null); if (Object.keys(next).length) return; setSaving(true); try { const id = initial?.id; const save = { teachers: id ? () => scheduling.updateTeacher(id, values as TeacherInput) : () => scheduling.createTeacher(values as TeacherInput), classes: id ? () => scheduling.updateClass(id, values as unknown as SchoolClassInput) : () => scheduling.createClass(values as unknown as SchoolClassInput), rooms: id ? () => scheduling.updateRoom(id, values as RoomInput) : () => scheduling.createRoom(values as RoomInput) }[kind] as () => Promise<unknown>; await save(); notify(initial ? 'Changes saved.' : 'Added.', 'success'); onSaved() } catch (err) { setFormError(friendlyApiError(err, 'save those details')) } finally { setSaving(false) } }
  return <section className="card section"><h2 className="section__title">{initial ? `Edit ${TITLES[kind].singular}` : `New ${TITLES[kind].singular}`}</h2>{formError && <Alert tone="error">{formError}</Alert>}<form className="form form--grid" onSubmit={submit} noValidate><Field label="Name" required value={String(values.name ?? '')} onChange={event => set('name', event.target.value)} error={errors.name} /><Field label="Code" required value={String(values.code ?? '')} onChange={event => set('code', event.target.value)} error={errors.code} />{kind === 'teachers' && <><Field label="Department" value={String(values.department ?? '')} onChange={event => set('department', event.target.value)} /><Field label="Maximum lessons per day" type="number" min={1} max={20} required value={String(values.max_lessons_per_day ?? 7)} onChange={event => set('max_lessons_per_day', Number(event.target.value))} /></>}{kind === 'classes' && <><Field label="Grade" value={String(values.grade ?? '')} onChange={event => set('grade', event.target.value)} /><Field label="Students" type="number" min={1} max={500} required value={String(values.student_count ?? 30)} onChange={event => set('student_count', Number(event.target.value))} error={errors.student_count} /></>}{kind === 'rooms' && <><Field label="Room type" value={String(values.room_type ?? 'standard')} onChange={event => set('room_type', event.target.value)} /><Field label="Capacity" type="number" min={1} max={500} value={String(values.capacity ?? 30)} onChange={event => set('capacity', Number(event.target.value))} /><Field label="Building" value={String(values.building ?? '')} onChange={event => set('building', event.target.value)} /></>}<div className="form__row form--grid__full"><button className="button button--primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button><button className="button button--secondary" type="button" onClick={onCancel}>Cancel</button></div></form></section>
}

function defaults(kind: Exclude<Kind, 'subjects'>, initial: Row | null) { if (kind === 'teachers') { const row = initial as Teacher | null; return { name: row?.name ?? '', code: row?.code ?? '', department: row?.department ?? '', max_lessons_per_day: row?.max_lessons_per_day ?? 7 } }; if (kind === 'classes') { const row = initial as SchoolClass | null; return { name: row?.name ?? '', code: row?.code ?? '', grade: row?.grade ?? '', student_count: row?.student_count ?? 30 } }; const row = initial as Room | null; return { name: row?.name ?? '', code: row?.code ?? '', room_type: row?.room_type ?? 'standard', capacity: row?.capacity ?? 30, building: row?.building ?? '' } }
