import { useCallback, useEffect, useMemo, useState } from 'react'
import './teachers.css'
import { PageHeader } from '../components/PageHeader'
import { EmptyState, ErrorState } from '../components/States'
import { DataTable, type Column } from '../components/DataTable'
import { SearchIcon, UserIcon } from '../components/icons'
import { useToast } from '../components/Toast'
import { friendlyApiError } from '../lib/api'
import { api, type Stream, type Grade } from '../lib/api'
import { scheduling, type Teacher, type SchoolClass } from '../lib/scheduling'

type Role='HOI/Principal'|'Deputy head of Institution'|'Senior Teacher'|'DOS'|'Class Teacher'|'HoD'|'Teacher'
const ROLES:Role[]=['HOI/Principal','Deputy head of Institution','Senior Teacher','DOS','Class Teacher','HoD','Teacher']
type Form={name:string;phone:string;email:string;code:string;department:string;role:Role;assignment:string}
type AssignmentOption={streamId:number;label:string;grade:string;stream:Stream;classId?:number}
const emptyForm:Form={name:'',phone:'',email:'',code:'',department:'',role:'Teacher',assignment:''}
const teacherName=(t:Teacher)=>t.name||[t.first_name,t.last_name].filter(Boolean).join(' ')||'Unnamed teacher'
const classSortKey=(c:SchoolClass)=>`${(c.grade||'').trim().toLocaleLowerCase()}\u0000${c.name.trim().toLocaleLowerCase()}`
const sortClasses=(items:SchoolClass[])=>Array.from(new Map(items.map(c=>[c.id,c])).values()).sort((a,b)=>classSortKey(a).localeCompare(classSortKey(b),undefined,{numeric:true}))

export default function Teachers(){
 const {notify}=useToast(); const [teachers,setTeachers]=useState<Teacher[]>([]); const [classes,setClasses]=useState<SchoolClass[]>([]); const [assignmentOptions,setAssignmentOptions]=useState<AssignmentOption[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [query,setQuery]=useState(''); const [modalOpen,setModalOpen]=useState(false); const [editing,setEditing]=useState<Teacher|null>(null); const [form,setForm]=useState<Form>(emptyForm); const [saving,setSaving]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [ts,cs,years,grades]=await Promise.all([scheduling.teachers(),scheduling.classes(),api.academicYears(),api.grades()]);setTeachers(ts);const sorted=sortClasses(cs);setClasses(sorted);const year=years.find(y=>y.is_current)||years.slice().sort((a,b)=>b.id-a.id)[0];if(!year){setAssignmentOptions([]);return}const streamLists=await Promise.all(grades.filter(g=>g.status!==false).map(g=>api.streams(year.id,g.id)));const options:AssignmentOption[]=[];grades.filter(g=>g.status!==false).forEach((grade,index)=>{const streams=streamLists[index]||[];streams.filter(stream=>stream.status==='ACTIVE').forEach(stream=>{const classRow=sorted.find(c=>c.code===`STREAM-${stream.id}`)||sorted.find(c=>(c.grade===grade.name||c.grade===grade.code)&&c.name.toLowerCase().includes(stream.name.toLowerCase()));options.push({streamId:stream.id,grade:grade.name,label:`${grade.name} — ${stream.name}`,stream,classId:classRow?.id})})});setAssignmentOptions(options)}catch(err){setError(friendlyApiError(err,'load teachers, classes and academic streams'))}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const availableClasses=useMemo(()=>sortClasses(classes),[classes])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?teachers.filter(t=>teacherName(t).toLowerCase().includes(q)||(t.code??t.staff_number??'').toLowerCase().includes(q)):teachers},[teachers,query])
 const close=()=>{setModalOpen(false);setEditing(null);setForm(emptyForm)}
 const openNew=()=>{setEditing(null);setForm(emptyForm);setModalOpen(true)}
 const openEdit=(t:Teacher)=>{const a=(t as any).role_assignment||{};setEditing(t);setForm({name:teacherName(t),phone:t.phone||'',email:t.email||'',code:t.code||t.staff_number||'',department:t.department||'',role:(ROLES.includes(t.role as Role)?t.role:'Teacher') as Role,assignment:a.stream_id?String(a.stream_id):String(a.value||'')});setModalOpen(true)}
 const save=async()=>{if(!form.name.trim()){notify('Teacher name is required.','error');return}if(!form.code.trim()){notify('Teacher code is required.','error');return}if((form.role==='Class Teacher'||form.role==='HoD')&&!form.assignment){notify(`Select an assignment for ${form.role}.`,'error');return}setSaving(true);try{const streamOption=form.role==='Class Teacher'?assignmentOptions.find(o=>o.streamId===Number(form.assignment)):undefined;let classId=streamOption?.classId;if(streamOption&&!classId){const created=await scheduling.createClass({name:streamOption.label,code:`STREAM-${streamOption.streamId}`,grade:streamOption.grade,student_count:40,class_teacher_id:null,home_room_id:null,unavailable:{}});classId=created.id}const payload:any={name:form.name.trim(),code:form.code.trim(),phone:form.phone||null,email:form.email||null,department:form.department||null,role:form.role,role_assignment:{value:form.assignment,...(streamOption?{stream_id:streamOption.streamId,class_id:classId}: {})}};const saved=editing?await scheduling.updateTeacher(editing.id,payload):await scheduling.createTeacher(payload);if(streamOption){await api.updateStream(streamOption.streamId,{class_teacher_id:saved.id});if(classId)await scheduling.updateClass(classId,{class_teacher_id:saved.id} as any)}notify(editing?'Teacher updated.':'Teacher added.','success');close();await load()}catch(err){notify(friendlyApiError(err,'save teacher'),'error')}finally{setSaving(false)}}
 const remove=async(t:Teacher)=>{if(!window.confirm(`Delete ${teacherName(t)}? This cannot be undone.`))return;try{await scheduling.deleteTeacher(t.id);notify('Teacher deleted.','success');await load()}catch(err){notify(friendlyApiError(err,'delete teacher'),'error')}}
 const columns:Column<Teacher>[]=[{key:'name',header:'Name',render:r=><strong>{teacherName(r)}</strong>},{key:'phone',header:'Phone number',render:r=>r.phone||'—'},{key:'email',header:'Email',render:r=>r.email||'—'},{key:'code',header:'Code',render:r=>r.code||r.staff_number||'—'},{key:'department',header:'Department',render:r=>r.department||'—'},{key:'role',header:'Role',render:r=>r.role||'Teacher'},{key:'actions',header:'Actions',render:r=><div className="teacher-actions"><button type="button" className="button button--ghost button--sm" onClick={()=>openEdit(r)}>Edit</button><button type="button" className="button button--danger button--sm" onClick={()=>void remove(r)}>Delete</button></div>}]
 return <><PageHeader title="Teachers" description="Manage teacher profiles, departments and responsibilities." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Setup'},{label:'Teachers'}]}/>{error?<ErrorState title="Teachers could not load" message={error} onRetry={load}/>:<section className="card section"><div className="toolbar"><div className="search"><SearchIcon className="search__icon" width={18} height={18}/><label className="visually-hidden" htmlFor="teacher-search">Search teachers</label><input id="teacher-search" className="input input--search" type="search" placeholder="Search by name or code" value={query} onChange={e=>setQuery(e.target.value)}/></div><button type="button" className="button button--primary" onClick={openNew}>+ New teacher</button>{!loading&&<span className="toolbar__count">{filtered.length} of {teachers.length}</span>}</div><DataTable caption="Teachers" columns={columns} rows={filtered} rowKey={r=>r.id} loading={loading} loadingLabel="Loading teachers" empty={<EmptyState title="No teachers yet" description="Add the first teacher using New teacher." icon={<UserIcon width={22} height={22}/>}/>} /></section>}
 {modalOpen&&<div className="teacher-modal-backdrop"><div className="card teacher-modal teacher-profile-modal" role="dialog" aria-modal="true" aria-labelledby="teacher-profile-title"><div className="teacher-modal__header"><div><p className="eyebrow">Teacher profile</p><h2 id="teacher-profile-title" className="section__title">{editing?'Edit teacher':'New teacher'}</h2></div><button type="button" className="button button--ghost button--sm" onClick={close}>×</button></div><div className="teacher-form-grid"><label>Name<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name"/></label><label>Phone number <span className="optional">optional</span><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email <span className="optional">optional</span><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Code<input className="input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Staff code"/></label><label>Department<input className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Department"/></label><label>Role<select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role,assignment:''})}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label>{form.role==='Class Teacher'&&<label className="teacher-form-wide">Assign class teacher to<select className="input" value={form.assignment} onChange={e=>setForm({...form,assignment:e.target.value})}><option value="">Select grade / stream ({assignmentOptions.length} available)</option>{assignmentOptions.map(o=><option key={o.streamId} value={o.streamId}>{o.label}</option>)}{assignmentOptions.length===0&&availableClasses.map(c=><option key={`class-${c.id}`} value={c.id}>{c.grade?`${c.grade} — `:''}{c.name}</option>)}</select>{assignmentOptions.length===0&&<span className="form__note">No active academic streams are available. Add grades and streams under Academic Setup first.</span>}</label>}{form.role==='HoD'&&<label className="teacher-form-wide">Assign Head of Department to<input className="input" value={form.assignment} onChange={e=>setForm({...form,assignment:e.target.value})} placeholder="Department name"/></label>}</div><div className="teacher-modal__actions"><button type="button" className="button button--ghost" onClick={close}>Cancel</button><button type="button" className="button button--primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':editing?'Save changes':'Add teacher'}</button></div></div></div>}
 </>
}
