import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { useToast } from '../components/Toast'
import { timetableProjects, type TimetableProject } from '../lib/timetableProjects'

export function TimetableProjectsPage(){
  const {notify}=useToast(); const [projects,setProjects]=useState<TimetableProject[]>([]); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false)
  const load=async()=>{setLoading(true);try{setProjects(await timetableProjects.list())}catch(e){notify(e instanceof Error?e.message:'Could not load timetable projects','error')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const create=async()=>{if(!name.trim())return;setBusy(true);try{await timetableProjects.create({name:name.trim(),description:description.trim()||null});setName('');setDescription('');notify('Timetable project created.','success');await load()}catch(e){notify(e instanceof Error?e.message:'Could not create project','error')}finally{setBusy(false)}}
  const archive=async(p:TimetableProject)=>{try{await timetableProjects.update(p.id,{status:p.status==='archived'?'draft':'archived'});await load()}catch(e){notify(e instanceof Error?e.message:'Could not update project','error')}}
  const remove=async(p:TimetableProject)=>{if(!window.confirm(`Delete “${p.name}”? This deletes its timetable versions, not the shared school resources.`))return;try{await timetableProjects.remove(p.id);await load()}catch(e){notify(e instanceof Error?e.message:'Could not delete project','error')}}
  return <><PageHeader title="Timetable Projects" description="Create independent timetable scenarios while sharing the school's teachers, learners, classes, subjects and rooms." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable Projects'}]}/>
    <div className="card section"><h2 className="section__title">New project</h2><div className="form-grid"><label className="field"><span className="field__label">Project name</span><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter any project name"/></label><label className="field"><span className="field__label">Description</span><input className="input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional"/></label></div><button className="button button--primary button--sm" disabled={busy||!name.trim()} onClick={create}>Create project</button></div>
    <div className="card section"><div className="section__header"><div><h2 className="section__title">Projects</h2><p className="form__note">All projects use the same master school resources.</p></div></div>{loading?<p>Loading…</p>:projects.length===0?<p>No timetable projects yet.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Status</th><th>Versions</th><th>Actions</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><strong>{p.name}</strong>{p.description&&<div className="form__note">{p.description}</div>}</td><td>{p.status}</td><td>{p.current_version_id?'Current version available':'No version yet'}</td><td><div className="toolbar__group"><a className="button button--secondary button--sm" href={`/timetable?project_id=${p.id}`}>Open</a><button className="button button--ghost button--sm" onClick={()=>archive(p)}>{p.status==='archived'?'Restore':'Archive'}</button><button className="button button--ghost button--sm" onClick={()=>remove(p)}>Delete</button></div></td></tr>)}</tbody></table></div>}</div>
  </>
}
