import { useCallback, useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { EmptyState, ErrorState, LoadingBlock } from '../components/States'
import { Alert } from '../components/Alert'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { TimetableGrid, UNASSIGNED_DRAG_TYPE, type LessonMeta } from '../components/TimetableGrid'
import { CalendarIcon, CloseIcon, DuplicateIcon, TrashIcon, LockIcon, UnlockIcon, PrintIcon, DownloadIcon, MinusIcon, PlusIcon } from '../components/icons'
import { useToast } from '../components/Toast'
import { Link } from '../lib/router'
import { ApiError, friendlyApiError } from '../lib/api'
import { cachedFetch, formatSavedAt } from '../lib/offline'
import { activeDays, scheduling, type Alternative, type Calendar, type Conflict, type Explanation, type Lesson, type SchoolClass, type Subject, type Teacher, type Unassigned, type Version } from '../lib/scheduling'

type Bundle = { calendar: Calendar; version: Version | null; lessons: Lesson[]; teachers: Teacher[]; subjects: Subject[]; rooms: never[]; classes: SchoolClass[]; conflicts: Conflict[]; unassigned: Unassigned[] }
async function loadBundle(): Promise<Bundle> {
  const [calendar, version, teachers, subjects, rooms, classes] = await Promise.all([scheduling.calendar(), scheduling.currentVersion(), scheduling.teachers(), scheduling.subjects(), scheduling.rooms(), scheduling.classes()])
  const [lessons, conflicts, unassigned] = version ? await Promise.all([scheduling.lessons(version.id), scheduling.conflicts(version.id), scheduling.unassigned(version.id)]) : [[], [], []]
  return { calendar, version, lessons, teachers, subjects, rooms, classes, conflicts, unassigned } as Bundle
}
type Scope = 'all' | 'class' | 'teacher' | 'room' | 'subject'
type Filter = { scope: Scope; id: number | null }
const DAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
function computeCurrentSlot(calendar: Calendar | undefined): { day: number; period: number } | null {
  if (!calendar) return null
  const now = new Date(); const day = (now.getDay() + 6) % 7
  if (!calendar.days.filter((d) => d.is_active).some((d) => d.index === day)) return null
  const minutes = now.getHours() * 60 + now.getMinutes()
  const period = calendar.periods.find((p) => { if (!p.is_teaching) return false; const [sh, sm] = p.start_time.split(':').map(Number); const [eh, em] = p.end_time.split(':').map(Number); return minutes >= sh * 60 + sm && minutes < eh * 60 + em })
  return period ? { day, period: period.index } : null
}
function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000) }
function downloadText(content: string, filename: string, type: string) { downloadBlob(new Blob([content], { type }), filename) }

export function TimetablePage() {
  const { notify } = useToast()
  const [bundle, setBundle] = useState<Bundle | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [stale, setStale] = useState<number | null>(null)
  const [filter, setFilter] = useState<Filter>({ scope: 'all', id: null }); const [dayFilter, setDayFilter] = useState<number | null>(null); const [zoom, setZoom] = useState(1); const [dense, setDense] = useState(false)
  const [selected, setSelected] = useState<Lesson | null>(null); const [explanation, setExplanation] = useState<Explanation | null>(null); const [busy, setBusy] = useState(false); const [publishing, setPublishing] = useState(false); const [confirmingDelete, setConfirmingDelete] = useState<Lesson | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const result = await cachedFetch('timetable:workspace', loadBundle); setBundle(result.data); setStale(result.stale ? result.savedAt : null) } catch (err) { setError(friendlyApiError(err, 'load the timetable')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const [currentSlot, setCurrentSlot] = useState<{ day: number; period: number } | null>(null)
  useEffect(() => { const update = () => setCurrentSlot(computeCurrentSlot(bundle?.calendar)); update(); const timer = window.setInterval(update, 60000); return () => window.clearInterval(timer) }, [bundle])
  const meta: LessonMeta = useMemo(() => ({ subjects: new Map((bundle?.subjects ?? []).map((s) => [s.id, s])), teachers: new Map((bundle?.teachers ?? []).map((t) => [t.id, t])), rooms: new Map((bundle?.rooms ?? []).map((r) => [r.id, r])), classes: new Map((bundle?.classes ?? []).map((c) => [c.id, c])) }), [bundle])
  const conflicted = useMemo(() => { const ids = new Set<number>(); for (const conflict of bundle?.conflicts ?? []) if (conflict.severity === 'hard') conflict.lesson_ids.forEach((id) => ids.add(id)); return ids }, [bundle])
  const visible = useMemo(() => { let result = bundle?.lessons ?? []; if (filter.scope !== 'all' && filter.id !== null) { const key = { class: 'class_id', teacher: 'teacher_id', room: 'room_id', subject: 'subject_id' }[filter.scope] as 'class_id' | 'teacher_id' | 'room_id' | 'subject_id'; result = result.filter((lesson) => lesson[key] === filter.id) } if (dayFilter !== null) result = result.filter((lesson) => lesson.day_index === dayFilter); return result }, [bundle, filter, dayFilter])
  const hardCount = (bundle?.conflicts ?? []).filter((c) => c.severity === 'hard').length; const readOnly = bundle?.version?.status === 'published'
  const printTitle = filter.scope === 'class' && filter.id !== null ? (meta.classes.get(filter.id)?.name ?? 'Class Timetable') : filter.scope === 'teacher' && filter.id !== null ? (meta.teachers.get(filter.id)?.name ?? 'Teacher Timetable') : 'Whole School Timetable'
  const printClassTeacher = filter.scope === 'class' && filter.id !== null ? (() => { const item = meta.classes.get(filter.id); return item?.class_teacher_id ? (meta.teachers.get(item.class_teacher_id)?.name ?? null) : null })() : null
  async function handleMove(lesson: Lesson, day: number, period: number) {
    if (busy) return; setBusy(true); setExplanation(null)
    try { await scheduling.moveLesson(lesson.id, { day_index: day, period_index: period }); notify('Lesson moved.', 'success'); await load() }
    catch (err) { if (err instanceof ApiError && err.status === 409 && err.detail) { const detail = err.detail as { reasons?: Explanation['reasons']; alternatives?: Alternative[] }; setSelected(lesson); setExplanation({ allowed: false, reasons: detail.reasons ?? [], alternatives: detail.alternatives ?? [] }); notify('That move creates a conflict.', 'error') } else notify(friendlyApiError(err, 'move the lesson'), 'error') }
    finally { setBusy(false) }
  }
  async function handleAlternative(alternative: Alternative) { if (!selected) return; await handleMove(selected, alternative.day, alternative.period) }
  async function handleResize(lesson: Lesson, duration: number) {
    if (duration < 1 || duration > 10) return
    try { await scheduling.resizeLesson(lesson.id, duration); notify(`Duration changed to ${duration} ${duration === 1 ? 'period' : 'periods'}.`, 'success'); await load() }
    catch (err) { if (err instanceof ApiError && err.status === 409 && err.detail) { const detail = err.detail as { reasons?: Explanation['reasons']; alternatives?: Alternative[] }; setSelected(lesson); setExplanation({ allowed: false, reasons: detail.reasons ?? [], alternatives: detail.alternatives ?? [] }); notify('That duration creates a conflict.', 'error') } else notify(friendlyApiError(err, 'change the duration'), 'error') }
  }
  async function handlePatch(lesson: Lesson, patch: Parameters<typeof scheduling.patchLesson>[1], success: string) { if (busy) return; setBusy(true); setExplanation(null); try { const updated = await scheduling.patchLesson(lesson.id, patch); setSelected(updated); notify(success, 'success'); await load() } catch (err) { notify(friendlyApiError(err, success), 'error') } finally { setBusy(false) } }
  async function handleDropUnassigned(requirementId: number, day: number, period: number) { if (!bundle?.version || readOnly) return; try { await scheduling.createLesson(bundle.version.id, { requirement_id: requirementId, day_index: day, period_index: period }); notify('Lesson scheduled.', 'success'); await load() } catch (err) { notify(friendlyApiError(err, 'schedule that lesson'), 'error') } }
  async function handleDuplicate() { if (!selected) return; try { await scheduling.duplicateLesson(selected.id); notify('Lesson duplicated.', 'success'); await load() } catch (err) { notify(friendlyApiError(err, 'duplicate the lesson'), 'error') } }
  async function handleDelete() { if (!confirmingDelete) return; const target = confirmingDelete; setConfirmingDelete(null); try { await scheduling.deleteLesson(target.id); if (selected?.id === target.id) setSelected(null); notify('Lesson deleted.', 'success'); await load() } catch (err) { notify(friendlyApiError(err, 'delete the lesson'), 'error') } }
  async function handlePublish() { if (!bundle?.version || publishing) return; setPublishing(true); try { await scheduling.publish(bundle.version.id); notify('Timetable published.', 'success'); await load() } catch (err) { notify(friendlyApiError(err, 'publish the timetable'), 'error') } finally { setPublishing(false) } }
  function exportCsv() { if (!bundle) return; const rows = [['Day','Period','Start','Subject','Class','Teacher','Room','Duration','Locked'], ...visible.map((lesson) => { const period = bundle.calendar.periods.find((p) => p.index === lesson.period_index); return [DAY_NAMES[lesson.day_index] ?? String(lesson.day_index), period?.name ?? String(lesson.period_index), period?.start_time ?? '', meta.subjects.get(lesson.subject_id)?.name ?? '', meta.classes.get(lesson.class_id)?.name ?? '', lesson.teacher_id ? (meta.teachers.get(lesson.teacher_id)?.name ?? '') : '', lesson.room_id ? (meta.rooms.get(lesson.room_id)?.name ?? '') : '', String(lesson.duration), lesson.is_locked ? 'yes' : 'no'] })]; downloadText(rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n'), 'timetable.csv', 'text/csv') }
  function exportIcs() { const lines = ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Phikila School Management System//Timetable//EN']; for (const lesson of visible) { const period = bundle?.calendar.periods.find((p) => p.index === lesson.period_index); const subject = meta.subjects.get(lesson.subject_id)?.name ?? 'Lesson'; lines.push('BEGIN:VEVENT', `UID:lesson-${lesson.id}@phikila`, `SUMMARY:${subject}`, `DESCRIPTION:${meta.classes.get(lesson.class_id)?.name ?? ''}`, 'END:VEVENT') }; lines.push('END:VCALENDAR'); downloadText(lines.join('\r\n'), 'timetable.ics', 'text/calendar') }
  function exportPng() {
    if (!bundle) return
    const periods = bundle.calendar.periods.filter((p) => p.is_teaching); const dayList = days; const scale = 2; const left = 150; const top = 92; const col = Math.max(150, Math.floor(1100 / Math.max(1, dayList.length))); const row = 62; const width = Math.min(2200, left + col * Math.max(1, dayList.length)); const height = top + row * Math.max(1, periods.length) + 40
    const canvas = document.createElement('canvas'); canvas.width = width * scale; canvas.height = height * scale; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.scale(scale, scale); ctx.fillStyle = '#fff'; ctx.fillRect(0,0,width,height); ctx.fillStyle = '#0F2A47'; ctx.font = '700 20px Arial'; ctx.fillText(printTitle, 20, 30); ctx.font = '12px Arial'; ctx.fillStyle = '#555'; ctx.fillText(`Version ${bundle.version?.number ?? ''} · exported ${new Date().toLocaleString()}`, 20, 52)
    ctx.strokeStyle = '#9aa5b1'; ctx.lineWidth = 1; ctx.fillStyle = '#eef2f6'; ctx.fillRect(0, top, left, row); ctx.fillStyle = '#1f2937'; ctx.font = '700 12px Arial'; ctx.fillText('Period / Time', 12, top + 25)
    dayList.forEach((day, i) => { const x = left + i * col; ctx.fillStyle = '#eef2f6'; ctx.fillRect(x, top, col, row); ctx.fillStyle = '#1f2937'; ctx.font = '700 12px Arial'; ctx.fillText(day.name, x + 8, top + 22); ctx.font = '10px Arial'; ctx.fillText(day.short_name ?? '', x + 8, top + 39); ctx.strokeRect(x, top, col, row) })
    periods.forEach((period, r) => { const y = top + (r + 1) * row; ctx.fillStyle = '#fafafa'; ctx.fillRect(0,y,left,row); ctx.fillStyle = '#1f2937'; ctx.font = '700 11px Arial'; ctx.fillText(period.name, 12, y + 22); ctx.font = '10px Arial'; ctx.fillText(`${period.start_time}–${period.end_time}`, 12, y + 39); ctx.strokeRect(0,y,left,row); dayList.forEach((day,i) => ctx.strokeRect(left+i*col,y,col,row)) })
    const selectedVisible = visible.filter((lesson) => lesson.day_index >= 0 && lesson.period_index !== undefined); selectedVisible.forEach((lesson) => { const di = dayList.findIndex((d) => d.index === lesson.day_index); const pi = periods.findIndex((p) => p.index === lesson.period_index); if (di < 0 || pi < 0) return; const x = left + di * col + 3; const y = top + (pi + 1) * row + 3; const h = Math.max(1, lesson.duration ?? 1) * row - 6; const subject = meta.subjects.get(lesson.subject_id); const cls = meta.classes.get(lesson.class_id); const teacher = lesson.teacher_id ? meta.teachers.get(lesson.teacher_id) : undefined; ctx.fillStyle = subject?.colour && /^#[0-9a-f]{6}$/i.test(subject.colour) ? subject.colour : '#dbeafe'; ctx.fillRect(x,y,col-6,h); ctx.strokeStyle = '#334155'; ctx.strokeRect(x,y,col-6,h); ctx.fillStyle = '#111827'; ctx.font = '700 10px Arial'; ctx.fillText(subject?.code ?? subject?.name ?? 'Lesson', x+6, y+17); ctx.font = '9px Arial'; if (cls) ctx.fillText(cls.name, x+6, y+31); if (teacher) ctx.fillText(teacher.code ?? teacher.name, x+6, y+44) })
    canvas.toBlob((blob) => { if (blob) downloadBlob(blob, 'timetable.png') }, 'image/png')
  }
  if (loading) return <><PageHeader title="Timetable" description="The current working timetable."/><div className="card section"><LoadingBlock label="Loading the timetable" rows={8}/></div></>
  if (error) return <><PageHeader title="Timetable"/><ErrorState title="Timetable could not load" message={error} onRetry={load}/></>
  const version = bundle?.version; const days = activeDays(bundle?.calendar.days ?? []); const selectedIsConflicted = selected ? conflicted.has(selected.id) : false
  return <>
    <PageHeader title="Timetable - Whole School" description={version ? `Version ${version.number} · ${version.status}` : 'No timetable has been generated yet.'} breadcrumbs={[{ label: 'Dashboard', to: '/' }, { label: 'Timetable' }]} actions={<><Link className="button button--secondary button--sm" to="/scheduling/generate">Generate</Link>{version && version.status !== 'published' && <button type="button" className="button button--primary button--sm" onClick={handlePublish} disabled={publishing || hardCount > 0}>{publishing ? 'Publishing…' : 'Publish'}</button>}</>}/>
    <style>{`@media print { .timetable-print-header { display:block!important; margin:0 0 4mm; padding:0 0 2mm; border-bottom:.35mm solid #111; text-align:center; font-family:Arial,Helvetica,sans-serif; color:#111 } .timetable-print-header h1{margin:0;font-size:7mm;line-height:1.05;font-weight:800}.timetable-print-header p{margin:1.5mm 0 0;font-size:3mm;line-height:1.1;font-weight:700} } .timetable-print-header{display:none}`}</style>
    <div className="timetable-print-header" aria-hidden="true"><h1>{printTitle}</h1>{printClassTeacher && <p>Class Teacher: {printClassTeacher}</p>}</div>
    {stale && <Alert tone="info" title="Offline copy">Showing the timetable saved on this device {formatSavedAt(stale)}. It will refresh when you are back online.</Alert>}
    {!version ? <div className="card section"><EmptyState title="No timetable yet" description="Add your teachers, subjects, classes and rooms, then generate a timetable." icon={<CalendarIcon width={22} height={22}/>} action={<Link className="button button--primary button--sm" to="/scheduling/generate">Generate a timetable</Link>}/></div> : <>
      <div className="card section timetable-controls-card"><div className="timetable-controls-row"><div className="timetable-control-group"><label className="field__label" htmlFor="tt-scope">View</label><select id="tt-scope" className="input input--select" value={filter.scope} onChange={(event) => setFilter({ scope: event.target.value as Scope, id: null })}><option value="all">Whole school</option><option value="class">By class / student</option><option value="teacher">By teacher</option><option value="room">By room</option><option value="subject">By subject</option></select></div><div className="timetable-control-group"><span className="field__label">Days</span><div className="day-chips"><button type="button" className={`day-chip ${dayFilter === null ? 'day-chip--active' : ''}`} onClick={() => setDayFilter(null)}>All days</button>{days.map((day) => <button key={day.index} type="button" className={`day-chip ${dayFilter === day.index ? 'day-chip--active' : ''}`} onClick={() => setDayFilter(dayFilter === day.index ? null : day.index)}>{day.name.slice(0,3)}</button>)}</div></div><div className="toolbar__spacer"/><div className="toolbar__group"><button type="button" className="button button--ghost button--sm" onClick={() => window.print()}><PrintIcon width={14} height={14}/> Print</button><button type="button" className="button button--ghost button--sm" onClick={exportCsv}>CSV</button><button type="button" className="button button--ghost button--sm" onClick={exportIcs}>Calendar</button><button type="button" className="button button--primary button--sm" onClick={exportPng}><DownloadIcon width={14} height={14}/> PNG</button></div></div>
      <div className="timetable-controls-row timetable-controls-row--secondary">{filter.scope !== 'all' && <div className="timetable-control-group"><label className="field__label" htmlFor="tt-target">{filter.scope === 'class' ? 'Class' : filter.scope === 'teacher' ? 'Teacher' : filter.scope === 'room' ? 'Room' : 'Subject'}</label><select id="tt-target" className="input input--select" value={filter.id ?? ''} onChange={(event) => setFilter((current) => ({ ...current, id: event.target.value ? Number(event.target.value) : null }))}><option value="">Choose…</option>{(filter.scope === 'class' ? bundle.classes : filter.scope === 'teacher' ? bundle.teachers : filter.scope === 'room' ? bundle.rooms : bundle.subjects).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>}<div className="toolbar__spacer"/><div className="toolbar__group"><button type="button" className="icon-button icon-button--subtle" title="Zoom out" onClick={() => setZoom((z) => Math.max(.75, z - .25))} disabled={zoom <= .75}><MinusIcon width={16} height={16}/></button><span className="toolbar__zoom-label">{Math.round(zoom * 100)}%</span><button type="button" className="icon-button icon-button--subtle" title="Zoom in" onClick={() => setZoom((z) => Math.min(1.25, z + .25))} disabled={zoom >= 1.25}><PlusIcon width={16} height={16}/></button><button type="button" className={`button button--ghost button--sm ${dense ? 'button--active' : ''}`} onClick={() => setDense((d) => !d)}>Compact</button></div></div></div>
      {readOnly && <Alert tone="info" title="Published timetable">Published versions are read-only so everyone sees the same schedule. Restore it as a draft from <Link to="/versions">Versions</Link> to make changes.</Alert>}
      {!readOnly && bundle.unassigned.length > 0 && <div className="card section unassigned"><div className="unassigned__head"><h2 className="section__title">Unassigned lessons</h2><p className="form__note">Drag a chip onto the grid to schedule it. {bundle.unassigned.length} remaining.</p></div><ul className="unassigned__list">{bundle.unassigned.map((item) => <li key={item.requirement_id}><button type="button" className="unassigned-chip" draggable onDragStart={(event) => { event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData(UNASSIGNED_DRAG_TYPE, String(item.requirement_id)) }}><span className="unassigned-chip__subject">{item.subject_name}</span><span className="unassigned-chip__class">{item.class_name}</span></button></li>)}</ul></div>}
      <div className="workspace timetable-workspace"><div className="card section workspace__grid"><TimetableGrid days={days} periods={bundle.calendar.periods} lessons={visible} meta={meta} view={filter.scope === 'class' ? 'class' : filter.scope === 'teacher' ? 'teacher' : 'whole-school'} conflicted={conflicted} selectedId={selected?.id ?? null} readOnly={readOnly || busy} zoom={zoom} dense={dense} currentSlot={currentSlot} onSelect={(lesson) => { setSelected(lesson); setExplanation(null) }} onMove={handleMove} onResize={handleResize} onDropUnassigned={handleDropUnassigned} secondary={(lesson) => filter.scope === 'class' ? null : (meta.classes.get(lesson.class_id)?.name ?? null)}/></div>
        <aside className="workspace__panel" aria-label="Lesson details">{selected ? <div className="card section"><div className="panel__head"><h2 className="section__title"><span className="subject-swatch" style={{ background: meta.subjects.get(selected.subject_id)?.colour ?? '#0F2A47' }} aria-hidden="true"/>{meta.subjects.get(selected.subject_id)?.name ?? 'Lesson'}</h2><button type="button" className="icon-button icon-button--subtle" onClick={() => { setSelected(null); setExplanation(null) }} aria-label="Close lesson details"><CloseIcon width={16} height={16}/></button></div>
          {selectedIsConflicted && <Alert tone="error" title="This lesson has a conflict">See the conflicts list below for the exact reason.</Alert>}
          {explanation && <Alert tone={explanation.allowed ? 'success' : 'warning'} title={explanation.allowed ? 'Move allowed' : 'Move blocked'}><div className="stack stack--xs">{explanation.reasons?.map((reason) => <div key={reason.code}>{reason.message}</div>)}{!explanation.allowed && explanation.alternatives?.length > 0 && <div><strong>Available alternatives</strong><div className="panel__actions" style={{ marginTop: 8 }}>{explanation.alternatives.map((alternative) => <button key={`${alternative.day}-${alternative.period}`} type="button" className="button button--secondary button--sm" disabled={busy} onClick={() => void handleAlternative(alternative)}>{alternative.day_name} · {alternative.period_name}</button>)}</div></div>}</div></Alert>}
          {selected.is_locked && <Alert tone="info" title="Locked">This lesson stays in its slot when the timetable is regenerated.</Alert>}
          <dl className="detail-list"><div><dt>Slot</dt><dd>{days.find((d) => d.index === selected.day_index)?.name}, {bundle.calendar.periods.find((p) => p.index === selected.period_index)?.name}{selected.duration > 1 && ` · ${selected.duration} periods`}</dd></div><div><dt>Class</dt><dd>{meta.classes.get(selected.class_id)?.name ?? '—'}</dd></div><div><dt>Teacher</dt><dd>{selected.teacher_id ? (meta.teachers.get(selected.teacher_id)?.name ?? '—') : 'Unassigned'}</dd></div><div><dt>Room</dt><dd>{selected.room_id ? (meta.rooms.get(selected.room_id)?.name ?? '—') : 'No room'}</dd></div></dl>
          {!readOnly && !selected.is_locked && <div className="panel__actions"><button type="button" className="button button--secondary button--sm" onClick={() => void handleResize(selected, Math.max(1, selected.duration - 1))} disabled={selected.duration <= 1 || busy}>− Shorten</button><button type="button" className="button button--secondary button--sm" onClick={() => void handleResize(selected, Math.min(10, selected.duration + 1))} disabled={selected.duration >= 10 || busy}>+ Extend</button></div>}
          {readOnly ? <p className="form__note">Published timetables are read-only.</p> : <div className="panel__actions"><button type="button" className="button button--secondary button--sm" onClick={() => void handlePatch(selected, { is_locked: !selected.is_locked }, selected.is_locked ? 'Lesson unlocked.' : 'Lesson locked.')}>{selected.is_locked ? <UnlockIcon width={14} height={14}/> : <LockIcon width={14} height={14}/>} {selected.is_locked ? 'Unlock' : 'Lock'}</button><button type="button" className="button button--secondary button--sm" onClick={handleDuplicate}><DuplicateIcon width={14} height={14}/> Duplicate</button><button type="button" className="button button--danger button--sm" onClick={() => setConfirmingDelete(selected)}><TrashIcon width={14} height={14}/> Delete</button></div>}
        </div> : <div className="card section"><EmptyState title="No lesson selected" description="Choose a lesson in the grid to see its details." icon={<CalendarIcon width={22} height={22}/>} /></div>}</aside>
      </div>
    </>}
    {confirmingDelete && <ConfirmDialog open title="Delete this lesson?" description="The selected lesson will be removed from the timetable." confirmLabel="Delete lesson" destructive onConfirm={handleDelete} onCancel={() => setConfirmingDelete(null)}/>} 
  </>
}
