import { useCallback, useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Badge, EmptyState, ErrorState } from '../components/States'
import { DataTable, type Column } from '../components/DataTable'
import { LayersIcon } from '../components/icons'
import { useToast } from '../components/Toast'
import { useNavigate } from '../lib/router'
import { friendlyApiError } from '../lib/api'
import { scheduling, type AuditEntry, type Version } from '../lib/scheduling'
import { VersionCompare } from '../components/VersionCompare'

function when(value: string | null) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString() }
type VersionWithDays = Version & { day_names?: string[] }

export function VersionsPage() {
  const { notify } = useToast(); const navigate = useNavigate()
  const [versions, setVersions] = useState<Version[]>([]); const [audit, setAudit] = useState<AuditEntry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<number | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [v, a] = await Promise.all([scheduling.versions(), scheduling.audit(40)]); setVersions(v); setAudit(a) } catch (e) { setError(friendlyApiError(e, 'load timetables')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  async function createDraft(v: Version) { setBusy(v.id); try { const draft = await scheduling.restore(v.id); notify(`Created editable draft v${draft.number} from v${v.number}.`, 'success'); await load(); navigate(`/timetable?version=${draft.id}`) } catch (e) { notify(friendlyApiError(e, 'create an editable draft'), 'error') } finally { setBusy(null) } }
  async function publish(v: Version) { setBusy(v.id); try { await scheduling.publish(v.id); notify(`Published ${v.label || `v${v.number}`}.`, 'success'); await load() } catch (e) { notify(friendlyApiError(e, 'publish that timetable'), 'error') } finally { setBusy(null) } }
  const columns: Column<Version>[] = [{ key: 'number', header: 'Version', render: r => `v${r.number}` }, { key: 'label', header: 'Timetable', render: r => r.label || 'Generated' }, { key: 'days', header: 'Working days', render: r => { const v = r as VersionWithDays; return v.day_names?.length ? v.day_names.join(', ') : '—' } }, { key: 'status', header: 'Status', render: r => <Badge tone={r.status === 'published' ? 'success' : r.status === 'archived' ? 'neutral' : 'warning'}>{r.status === 'draft' ? 'editable draft' : r.status === 'published' ? 'published · read-only' : 'archived · read-only'}</Badge> }, { key: 'quality', header: 'Quality', render: r => r.quality?.overall !== undefined ? `${r.quality.overall}/100` : '—' }, { key: 'lessons', header: 'Lessons', render: r => String(r.stats?.placed ?? '—') }, { key: 'created', header: 'Created', render: r => when(r.created_at) }]
  return <><PageHeader title="Timetables" description="Create, compare, edit copies, publish and preserve independent timetable configurations." breadcrumbs={[{ label: 'Dashboard', to: '/' }, { label: 'Timetables' }]} actions={<button type="button" className="button button--primary" onClick={() => navigate('/scheduling/generate')}>New Timetable</button>} />{error ? <ErrorState title="Timetables could not load" message={error} onRetry={load} /> : <><section className="card section"><div className="panel__head"><div><h2 className="section__title">Saved timetables</h2><p className="form__note">Open saved versions for review. Published and archived versions are read-only; use Edit copy to create a new draft.</p></div><Badge>{versions.length} saved</Badge></div><DataTable caption="Saved timetables" columns={columns} rows={versions} rowKey={r => r.id} loading={loading} loadingLabel="Loading timetables" empty={<EmptyState title="No timetables yet" description="Create your first timetable, then create another without overwriting it." icon={<LayersIcon width={22} height={22} />} />} rowActions={row => <><button type="button" className="button button--ghost button--sm" onClick={() => navigate(`/timetable?version=${row.id}`)}>{row.status === 'draft' ? 'Open' : 'Review'}</button>{row.status === 'draft' && <button type="button" className="button button--ghost button--sm" onClick={() => void publish(row)} disabled={busy === row.id}>Publish</button>}<button type="button" className="button button--ghost button--sm" onClick={() => void createDraft(row)} disabled={busy === row.id}>{busy === row.id ? 'Creating…' : 'Edit copy'}</button></>} /></section>{versions.length > 1 && <VersionCompare versions={versions} />}<section className="card section"><h2 className="section__title">Audit log</h2>{audit.length === 0 ? <EmptyState title="No activity yet" description="Changes to timetables are recorded here." /> : <ol className="audit-list">{audit.map(entry => <li className="audit-item" key={entry.id}><span className="audit-item__time">{when(entry.at)}</span><div className="audit-item__body"><p className="audit-item__summary">{entry.summary}</p><p className="audit-item__meta"><Badge>{entry.action}</Badge> {entry.actor || 'system'}</p>{entry.before && entry.after && <p className="audit-item__diff">{JSON.stringify(entry.before)} → {JSON.stringify(entry.after)}</p>}</div></li>)}</ol>}</section></>}</>
}
