import { useCallback, useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Badge, EmptyState, ErrorState } from '../components/States'
import { useToast } from '../components/Toast'
import { useNavigate } from '../lib/router'
import { friendlyApiError } from '../lib/api'
import { scheduling, type Version } from '../lib/scheduling'

function when(value:string|null|undefined){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString()}
export function VersionsPage(){
 const {notify}=useToast();const navigate=useNavigate();const [versions,setVersions]=useState<Version[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState<number|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setVersions(await scheduling.versions())}catch(e){setError(friendlyApiError(e,'load timetable versions'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])
 async function publish(version:Version){if(busy!==null)return;setBusy(version.id);try{await scheduling.publish(version.id);notify('Timetable is now in force.','success');await load()}catch(e){notify(friendlyApiError(e,'publish the timetable'),'error')}finally{setBusy(null)}}
 async function restore(version:Version){if(busy!==null)return;setBusy(version.id);try{const draft=await scheduling.restore(version.id);notify('Version restored as a new draft.','success');await load();navigate(`/timetable?version_id=${draft.id}`)}catch(e){notify(friendlyApiError(e,'restore the timetable version'),'error')}finally{setBusy(null)}}
 async function remove(version:Version){if(busy!==null)return;if(!window.confirm('Delete this draft timetable version?'))return;setBusy(version.id);try{await scheduling.deleteVersion(version.id);notify('Draft version deleted.','success');await load()}catch(e){notify(friendlyApiError(e,'delete the timetable version'),'error')}finally{setBusy(null)}}
 return <><PageHeader title="Timetable versions" description="Draft, test, review, publish and restore timetable versions without overwriting history." breadcrumbs={[{label:'Dashboard',to:'/'},{label:'Timetable'},{label:'Versions'}]} actions={<button type="button" className="button button--primary" onClick={()=>navigate('/scheduling/generate')}>Build new timetable</button>}/>{error?<ErrorState title="Timetable versions could not load" message={error} onRetry={load}/>:<section className="card section">{loading?<div className="form__note">Loading timetable history…</div>:versions.length===0?<EmptyState title="No timetable versions" description="Build a timetable to create the first draft version."/>:<div className="builder-table-wrap"><table className="builder-table"><thead><tr><th>Version</th><th>Status</th><th>Created</th><th>Published</th><th>Actions</th></tr></thead><tbody>{versions.map(version=><tr key={version.id}><td><strong>{version.label||version.name||`Timetable ${version.number??version.id}`}</strong><div className="form__note">#{version.number??version.id}</div></td><td><Badge tone={version.status==='published'?'success':version.status==='archived'?'neutral':'warning'}>{version.status}</Badge></td><td>{when(version.created_at)}</td><td>{when(version.published_at)}</td><td><div className="builder-actions"><button type="button" className="button button--secondary button--sm" onClick={()=>navigate(`/timetable?version_id=${version.id}`)}>Review</button>{version.status!=='published'&&<button type="button" className="button button--primary button--sm" onClick={()=>void publish(version)} disabled={busy!==null}>{busy===version.id?'Publishing…':'Publish'}</button>}{<button type="button" className="button button--ghost button--sm" onClick={()=>void restore(version)} disabled={busy!==null}>{busy===version.id?'Restoring…':'Restore as draft'}</button>}{version.status!=='published'&&<button type="button" className="button button--ghost button--sm" onClick={()=>void remove(version)} disabled={busy!==null}>Delete</button>}</div></td></tr>)}</tbody></table></div>}</section>}</>}
