create table if not exists public.finance_vote_heads (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.school_info(id),
  name text not null,
  code text,
  description text,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, code)
);
create table if not exists public.fee_structure_items (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.school_info(id),
  fee_structure_id bigint not null references public.fee_structures(id) on delete cascade,
  vote_head_id bigint not null references public.finance_vote_heads(id),
  amount numeric(14,2) not null check (amount >= 0),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (fee_structure_id, vote_head_id)
);
create table if not exists public.student_invoice_items (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.school_info(id),
  invoice_id bigint not null references public.student_invoices(id) on delete cascade,
  vote_head_id bigint references public.finance_vote_heads(id),
  description text,
  amount numeric(14,2) not null check (amount >= 0),
  balance numeric(14,2) not null check (balance >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.payment_allocations (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.school_info(id),
  payment_id bigint not null references public.payments(id) on delete cascade,
  invoice_id bigint references public.student_invoices(id),
  invoice_item_id bigint references public.student_invoice_items(id),
  vote_head_id bigint references public.finance_vote_heads(id),
  amount numeric(14,2) not null check (amount > 0),
  allocation_type text not null default 'FEE' check (allocation_type in ('FEE','CREDIT','REVERSAL')),
  created_at timestamptz not null default now()
);
create table if not exists public.student_fee_credits (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.school_info(id),
  student_id bigint not null,
  source_payment_id bigint references public.payments(id),
  amount numeric(14,2) not null check (amount > 0),
  balance numeric(14,2) not null check (balance >= 0),
  status text not null default 'AVAILABLE' check (status in ('AVAILABLE','APPLIED','VOID')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_fee_structure_items_fee on public.fee_structure_items(fee_structure_id);
create index if not exists idx_invoice_items_invoice on public.student_invoice_items(invoice_id);
create index if not exists idx_payment_allocations_payment on public.payment_allocations(payment_id);
create index if not exists idx_payment_allocations_invoice on public.payment_allocations(invoice_id);
create index if not exists idx_student_fee_credits_student on public.student_fee_credits(student_id,status);
alter table public.finance_vote_heads enable row level security;
alter table public.fee_structure_items enable row level security;
alter table public.student_invoice_items enable row level security;
alter table public.payment_allocations enable row level security;
alter table public.student_fee_credits enable row level security;
