DEFAULT_CLASS_CAPACITY = 45

CLASS_STATUS_ACTIVE = "Active"
CLASS_STATUS_INACTIVE = "Inactive"
CLASS_STATUS_ARCHIVED = "Archived"

ALLOWED_CLASS_STATUSES = {
    CLASS_STATUS_ACTIVE,
    CLASS_STATUS_INACTIVE,
    CLASS_STATUS_ARCHIVED,
}